### ISSUE TITLE
How to implement partial sync in Xamarin.Forms

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-dotnet#1683] opened 2018-02-05 08:14 UTC
@AlonikiX commented on [Mon Jan 22 2018](https://github.com/realm/realm-object-server/issues/337)

Hi, when I try to use `realm.SubscribeToObjectsAsync<T>()`, it simply throws me error messages but without crashing the program, neither stopping on the breakpoint.
`Connection[1]: Connected to endpoint '174.129.178.67:9080' (from '192.168.0.29:62626')
Connection[1]: Received: ERROR(error_code=208, message_size=34, try_again=0, session_ident=1)
Connection[1]: Connection closed due to error reported by server: Bad client file identifier (IDENT) (208)`.

Here is the code:
![d011e771-5632-4b56-a501-3a8e7056aacc](https://user-images.githubusercontent.com/11833091/35205932-2a69477c-ff8d-11e7-821b-104a2442314d.png)

The `user.Identity` is valid, I can use it to query data.

Need helps, thanks.

---

@bmunkholm commented on [Mon Feb 05 2018](https://github.com/realm/realm-object-server/issues/337#issuecomment-363010227)

I'll move this issue to the .Net repo to get you proper help.

**Comment by AlonikiX** [comment] 2018-02-05 09:01
Thanks for you help. In fact I already solved it out, it seems the error is caused by the unmatched schema, I simply create a new realm file and everything works fine. I forgot to close this issue, sorry.

**Comment by nirinchev** [comment] 2018-02-05 11:56
Glad to hear you solved it.

**Closed by nirinchev** 2018-02-05 11:56 UTC
