### ISSUE TITLE
Error on inheritance?

### ISSUE THREAD

**Issue by stephenhauck** [realm/realm-dotnet#959] opened 2016-11-30 22:10 UTC
I am building a system with Xamarin and another object database and wanted to switch to Realm but I have an issue ......

I am getting this error :Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody/RealmWeaver: The type CommScV2.Models.Metadata.Route indirectly inherits from RealmObject which is not supported.	CommScV2			

I have a model like such:

 public class MetadataBase : RealmObject
    {
    }

Then I have a model like such:
  public class Route : MetadataBase
    {
}

Not seeing the problem here ......

I have TONS of classes like this due to integration with an existing WCF web service.

Thanks for any help you can offer.....

**Comment by AndyDentFree** [comment] 2016-12-01 02:05
Hi @stephenhauck 
The problem is, as described in the Fody error, _ indirectly inherits from RealmObject which is not supported_

We currently required you to inherit directly from `RealmObject` without an intermediate class such as your `MetadataBase`.

We do understand that is a pain for some people. The main reason is we do not yet support composing inherited objects in the core Realm.

I am closing your issue as a duplicate of the original #529 and if you would like to add more detail about your expectations there they would be very much appreciated.

One possibility for the .NET SDK is that, if your intermediate classes do not add any persistent properties, but just behaviour, we could relax the constraint. However, there would still be issues if you wanted to write a query on the common base class - you can only query the _leaf_ classes as they are the ones in the Realm store.

**Closed by AndyDentFree** 2016-12-01 02:05 UTC

**Comment by stephenhauck** [comment] 2016-12-01 12:35
I have the base objects(I omitted the properties for brevity) and I am adding properties to them and extending them......

**Comment by AndyDentFree** [comment] 2016-12-01 13:39
The problem is that there's an extra class in the middle.

`Route : MetadataBase : RealmObject` is not yet supported

`Route : RealmObject` is what we need

**Comment by stephenhauck** [comment] 2016-12-01 13:41
Right.. is that a limitation of Fody ?

How would you extend a type without a bunch of code like automapper in a case like this that would work with Realm?

**Comment by AndyDentFree** [comment] 2016-12-01 13:50
>is that a limitation of Fody

No, it's a current limitation of the core Realm engine, which is why it is not supported in any other SDKs either.

We just have Fody give you the error message because it's a way to have a _compile-time check._

There's no way in the C# language to express such a constraint. (I think of it as _nearly sealed_ - you can only inherit one level down).

Regarding Automapper, have a look at the code in #833 and maybe talk to @eyadon.

We would love to have more samples of that kind of stuff especially a nice third-party how-to blog posting we could promote ;-)

**Comment by alexmartinezm** [comment] 2018-02-26 11:11
Is there any update about this?

**Comment by nirinchev** [comment] 2018-02-26 11:38
This issue is closed so there's no reason to expect it will ever be updated.

**Comment by paul-kiar** [comment] 2021-04-22 18:51
Why can we not have an abstract base class?

**Comment by nirinchev** [comment] 2021-04-22 19:40
This is a limitation of the current design of the SDK. We have plans to lift it in the future but it's not a trivial task and hasn't been a major pain point for most users which is why it hasn't been prioritized. Feel free to upvote and/or comment on the issue tracking that: https://github.com/realm/realm-dotnet/issues/529.

**Comment by paul-kiar** [comment] 2021-04-22 20:05
Our pain point is that our model has a hierarchy, every object has abstract base class properties:  Guid Primary Key, CreatedBy string, CreatedOn datetime,...   Then we have intermediate abstract base class properties that are shared by similar objects and then finally the class with the properties that only apply to it.  This is a common way to build object oriented programs.  Then we have UI that deals with only the intermediate abstract base class, and ui that deals with the final class type.  So yes, we can change and flatten our hierarchy, but that just means we have to duplicate all the properties on all the classes.  It's a one time migration cost, but I wouldn't call it an easy migration.

**Comment by alexmartinezm** [comment] 2021-04-22 20:08
I mean, this is a known limitation, you can always find an alternative to realm or just duplicate the properties across the project.

**Comment by nirinchev** [comment] 2021-04-22 20:27
> It's a one time migration cost, but I wouldn't call it an easy migration.

I agree - the current situation is less than ideal, which is why we'd like to address it at some point, but we just have more important issues to take care of right now. In your case, you could try moving those properties to interfaces and have your models implement the interface. It won't save you from having to duplicate the properties across all concrete implementations but should at least let you keep most of the app architecture intact (assuming you update your UI components to deal with the interfaces rather than the base classes).

**Comment by kyvarn** [comment] 2022-06-10 08:15
I would be interested to understand why in Swift you can inherit from a class that inherits from Realm Swifts Object  class while the same feature is not possible in .NET

**Comment by nirinchev** [comment] 2022-06-10 11:45
Those are different SDKs that have prioritized SDK-specific work based on the needs of their communities. We have not received enough feedback to indicate this is higher priority than some of the other tasks we're working on.
