### ISSUE TITLE
Add Insert support for large batched data sets

### ISSUE THREAD

**Issue by cmcnicholas** [realm/realm-dotnet#1959] opened 2020-02-17 18:39 UTC
## Goals

As indicated by the Java library they managed to vastly improve insertion by providing a more lightweight method. My use case is transitioning an application that syncs between 100k and 1 million records on a mobile device. This was previously SQLite and I was under the impression realm could potentially produce better performance. I'm not in need of the managed objects as they are created so it leads me to believe that optimisations could be made in the .Net library, see this post for Java improvements: https://realm.io/blog/realm-java-1-1-0/

## Expected Results

Even faster creation of records.

## Version of Realm and Tooling

- Realm Object Server Version: ? (you can see this as well in Studio once connected to a Realm instance) 
- Flavor:
  - [ ] Realm Cloud
  - [ ] Self-Hosted
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

**Comment by nirinchev** [comment] 2020-02-17 22:00
Can you share what insertion rates are you seeing for Realm vs SQLite? The Java and the .NET SDKs have very different architectures, so not many optimizations are directly applicable.

**Comment by cmcnicholas** [comment] 2020-02-17 23:31
thanks for the quick response. I am achieving ~2k inserts per second with pretty standard realm.net code (I believe so):

```
await realmInstance.WriteAsync((tx) =>
{
    foreach (var item in items)
    {
        // insert the item
        var insertedItem = tx.Add(item, false);
    }
});
```

I wouldn't consider my realm objects to be particularly large, a class with 8 string properties on them, one of them the PK and 2 indexed. The 2 indexed fields on our dataset range in size from 4-32 characters. The other properties have somewhere between 32-128 characters (dataset is variable).

Don't get me wrong, the speed is good but I am getting _almost_ comparable inserts into SQLite (this is all using Xamarin Forms on physical devices same environment). I figured from coming across that article that there is an overhead to retrieving the object inserted into realm via the `Add` function but I am happy to be told I am wrong about that :)

**Comment by fealebenpae** [comment] 2020-02-18 14:48
This sounds interesting. I'd like to spend some time at some point to profile to figure out whether there is anything to be gained by not "retrieving" the inserted object, as it were. Keep in mind, however, that the internal architecture of the Realm Java SDK is fairly different from that of the .NET SDK so while there are most likely some improvements we can make performance-wise, especially around compile-time code generation, what worked for Java in 2016 isn't guaranteed to be applicable for the .NET SDK now.

**Comment by cmcnicholas** [comment] 2021-02-26 15:21
Just was going through some of my opened tickets to see if any needed cleanup, realised the link above is now invalid with the move of website incorporating mongodb.

This is the PR that discusses the improvements made on the Java side: https://github.com/realm/realm-java/issues/1684

**Comment by nirinchev** [comment] 2021-02-26 15:53
Hey @cmcnicholas thanks for the follow-up here and I'm sorry we don't have anything to share yet. We don't have some of the issues addressed by the Java PR, so things _should_ be faster than what Java had before this optimization. That being said, there's one major area of improvement that can be addressed by bulk inserts and that's the number of times we cross the managed<->native boundary. That is by far the most expensive part of setting a property, so we can definitely benefit from reducing the number of calls by batching things together.

It hasn't been a major pain point, so we haven't prioritized it, but in the coming months, we'll be migrating to a completely new way of interoping between C# and native that will enable us to add batching support. Can't promise anything yet, but I'm optimistic that we will be able to look into batching sooner rather than later 😊

**Closed** 2022-03-18 12:24 UTC
Labels: T-Enhancement, O-Community

**Comment by nirinchev** [comment] 2022-03-18 13:01
Closed as duplicate of https://github.com/realm/realm-dotnet/issues/1751.
