### ISSUE TITLE
10.1.4 Creating Build Error for iOS target (XF solution)

### ISSUE THREAD

**Issue by dgerding** [realm/realm-dotnet#2378] opened 2021-05-14 20:57 UTC
## Goals
Tried updating from 10.1.3 to 10.1.4  realm-dotnet nuget package.

## Expected Results
Continued operation.

## Actual Results
Got the following error during build for iOS.
MessagingRemoteException: An error occurred on client Build169000292 while executing a reply for topic xvs/build/execute-task/appName.iOS/5c2edeb002fCodesign
AggregateException: One or more errors occurred.
DirectoryNotFoundException: Could not find a part of the path '/Users/davidgerding/Library/Caches/Xamarin/mtbs/builds/appName.iOS/5c2edeb1da9145e38b77d21bf03639cf474b6aa439e357820025632e07dc2a21/bin/iPhoneSimulator/Debug/appName.iOS.app/Frameworks/realm-wrappers.framework/_CodeSignature'.	appName.XF.iOS			

## Steps to Reproduce
Downgrading 10.1.3 makes build error go away. Tried twice both ways.

## Version of Realm and Tooling
10.1.3 and 10.1.4
Visual Studio 2019 (latest) on both Windows and Mac build machine . (Building from Windows)

**Comment by papafe** [comment] 2021-05-17 05:51
Hi @dgerding, have you tried removing the content of the build cache on the Mac? That is removing the subfolders of `Users/davidgerding/Library/Caches/Xamarin/mtbs/builds/`
Another thing that could be useful is doing a clean and removing also the obj/bin folders.

**Comment by papafe** [comment] 2021-05-21 06:33
Hi @dgerding did you manage to solve your issue?

**Comment by nirinchev** [comment] 2021-05-21 06:51
Someone on the forums has reported the same issue: https://developer.mongodb.com/community/forums/t/mongodb-realm-xamarin-forms-issue/107853/

**Comment by dgerding** [comment] 2021-05-26 01:16
> Hi @dgerding, have you tried removing the content of the build cache on the Mac? That is removing the subfolders of `Users/davidgerding/Library/Caches/Xamarin/mtbs/builds/`
> Another thing that could be useful is doing a clean and removing also the obj/bin folders.

I couldn't find the Xamarin folder along that path. I'll search for mtbs and report back.

**Comment by papafe** [comment] 2021-05-26 06:58
Hi @dgerding let us know how it goes. 
It could also be that you are seeing the same error as another user on the MongoDB forums [here](https://developer.mongodb.com/community/forums/t/mongodb-realm-xamarin-forms-issue/107853/5).  In that case the user is going around the issue temporarily by building directly on Mac.

**Comment by nirinchev** [comment] 2021-06-16 09:17
Likely duplicate of https://github.com/realm/realm-dotnet/issues/2448.

**Comment by papafe** [comment] 2021-07-06 12:39
@dgerding Did you possibly check if building directly on Mac works for you?

**Comment by nirinchev** [comment] 2021-07-10 11:15
This was a regression in VS for Windows which has now been addressed.

**Closed by nirinchev** 2021-07-10 11:15 UTC
Labels: More-information-needed, O-Community
