### ISSUE TITLE
IList does not update UWP ListView

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-dotnet#1883] opened 2019-07-14 04:49 UTC
I am just converting and app from C#/WPF to C#/UWP (Windows 10) and it seems that IList does not update the UWP ListView.  

So first question - should it ?  

and if not then how should I bind the IList property to ensure the ListView will update if items are added or removed?  

Maybe some more context - new items are getting created on a background thread - and the exact same method/code seems to work fine with C#/WPF.

```

<ListView x:Name="siteListView"  SelectionChanged="SiteListView_SelectionChanged" 
                             DataContext="{x:Bind _this}" 
ItemsSource="{x:Bind Customer.items, Mode=OneWay}"  >
...
```

```
public class Customer : RealmObject
    {
        [PrimaryKey]
        public string id { get; set; } = Guid.NewGuid().ToString();
        public string name { get; set; }

        public string address { get; set; }

        public string contact { get; set; }

        public float complianceScore { get; set; }
        public string completionStatus { get; set; }

        public IList<Site> sites { get; }

}
```

**Comment by nirinchev** [comment] 2019-07-14 11:38
This comment goes into a little bit of detail why this is happening: https://github.com/realm/realm-dotnet/issues/1759#issuecomment-407749262. I'll close this as a duplicate of #1759.

**Closed by nirinchev** 2019-07-14 11:38 UTC
Labels: O:User
