### ISSUE TITLE
Source generation doesn't support non-nullable object types

### ISSUE THREAD

**Issue by peppy** [realm/realm-dotnet#3085] opened 2022-11-09 09:10 UTC
### What happened?

We are keen to switch to the new source generator, but are blocked by it not supporting non-nullable object types. We have been using realm with non-nullable object types for a good year and it definitely works well, so I would hope that this can be supported by the source generator.

Currently it is disabled via this check:

https://github.com/realm/realm-dotnet/blob/a7b8f3a749d1a863ac617acee656bcf179ed7cd9/Realm/Realm.SourceGenerator/InfoClasses.cs#L250-L254

I'm not sure if this is to be considered a bug or feature request, but it's a blocker for us to use source generation unfortunately.

### Repro steps

- Create a class with non-nullable objects.
- Receive build errors.

### Version

6.x

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Other

### Client OS and version

10.18.0

### Code snippets

An example of a class that would work previously:

```csharp
public partial class RealmNamedFileUsage : IEmbeddedObject
{
    public RealmFile File { get; set; } = null!; // <- problematic line

    public string Filename { get; set; } = null!;

    public RealmNamedFileUsage(RealmFile file, string filename)
    {
        File = file ?? throw new ArgumentNullException(nameof(file));
        Filename = filename ?? throw new ArgumentNullException(nameof(filename));
    }

    private RealmNamedFileUsage()
    {
    }
}

[MapTo("File")]
public partial class RealmFile : IRealmObject
{
    [PrimaryKey]
    public string Hash { get; set; } = string.Empty;
}
```

Our codebase branch with all changes applied that we hope would make source generation work correctly: https://github.com/ppy/osu/compare/master...peppy:osu:realm-source-gen?expand=1

### Stacktrace of the exception/crash you're getting

```shell
Program.cs(19, 5): [RLM010] RealmNamedFileUsage.File has type RealmFile, that does not support the assigned nullability annotiation.
```

**Comment by nirinchev** [comment] 2022-11-09 10:15
The problem is that properties linking to realm objects are inherently nullable. Since you can always do something like:

```csharp
RealmNamedFileUsage usage = ...;
realm.Remove(usage.File);
```

Now, `usage.File` will be `null`, which makes the nullability annotation incorrect. While your app may not be doing that, there's no way to statically guarantee that, which is why we opted for the safer approach of requiring that all `RealmObject` properties are nullable.

**Comment by peppy** [comment] 2022-11-09 13:33
I completely understand that from a safety perspective. But I do wonder if some middle-ground can be offered as we value non-nullable specs on a lot of our models (and haven't had this go wrong for us.. yet).

**Comment by nirinchev** [comment] 2022-11-09 14:54
@papafe perhaps we can offer this as a config option? I.e. allow users to explicitly enable usage of non-nullable link properties? I guess we could still return null on our end and have them deal with the consequences 😅

**Comment by J-Swift** [comment] 2022-11-11 22:02
I would prefer the same as any on-the-wire deserialization API does (e.g. System.Text.Json, etc), namely you can declare the nullability however you want but that doesn't guarantee anything about the actual data. Its still up to the clients to not corrupt the underlying, and allowing the programmer to specify that it _shouldnt_ be null avoids a lot of noisy error handling throughout the entire codebase.

**Comment by papafe** [comment] 2022-11-14 10:06
I think we can offer that as a config option. We have several things in the pipeline, including full support for nullability annotations in the model definition (#2982).
Regarding completely ignoring nullability.... this is probably something that could be made into an option as well, we'd need to discuss it internally too though. Our idea here was to remove the need for attributes such as `[Required]` and let the nullability be the driven directly from the properties.

**Comment by J-Swift** [comment] 2022-11-17 20:35
I'm definitely in favor of moving to nullability declarations (and nullable reference types) as the source of truth and avoiding the need for `Required` attributes if thats what you're saying.

**Comment by papafe** [comment] 2022-11-18 07:38
@J-Swift Yes, that is the plan. I suppose that there are different opinions on how certain things should be done :)

**Comment by nirinchev** [comment] 2023-02-01 17:13
This should be addressed by #3172 which should go into our next release.

**Closed by nirinchev** 2023-02-01 17:13 UTC
Labels: O-Community

**Comment by peppy** [comment] 2023-02-17 13:21
Thanks for adding support for this!

I've been attempting to get it working but applying the ignore setting doesn't seem to immediately be doing anything:

![2023-02-17 22 20 35@2x](https://user-images.githubusercontent.com/191335/219663747-ea7ed662-6932-4312-ac59-a2e225c8093c.png)

It should be fine to place this in our existing `.editorconfig` at a solution level, correct?

**Comment by nirinchev** [comment] 2023-02-17 13:46
I think we're reading this option from the global config, so you should put it there. See https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files#global-analyzerconfig for more details.

**Comment by peppy** [comment] 2023-02-18 02:30
I see, this does indeed work!

May be worth updating the link [here](https://github.com/realm/realm-dotnet/blob/main/CHANGELOG.md?plain=1#LL67C398-L67C404) to point to the correct anchor on that page - as it stands I misunderstood which config file was supported.

**Comment by nirinchev** [comment] 2023-02-18 15:43
Can you post the generated code that's triggering these warnings? I'm afraid `RS0030` may be something you need to add an exemption for on your end but `CS8601` is surprising and we should probably fix the generator for that one.

**Comment by peppy** [comment] 2023-02-18 17:24
Here's the generated code from the above run:

[Realms.SourceGenerator.RealmGenerator.zip](https://github.com/realm/realm-dotnet/files/10774821/Realms.SourceGenerator.RealmGenerator.zip)

**Comment by peppy** [comment] 2023-02-20 16:12
For anyone interested, to disable inspection rules in source generators, it looks like you basically have to disable at a `.globalconfig` level then re-enable locally (see https://github.com/dotnet/roslyn/issues/47384). This works for me with [this change](https://github.com/peppy/osu/commit/7a9fc60fe19d95ab8bd3495dc4f898ed88d12c02).

I'm facing some remaining issues with source generation but I'll open a new discussion to keep things clean, as they are not nullability related.
