### ISSUE TITLE
Same user login generate a new Device ID

### ISSUE THREAD

**Issue by carbonete** [realm/realm-dotnet#2430] opened 2021-06-08 20:27 UTC
## Goals

When login user/mail at same device, not generate new Device ID, every time user logout and login again new device id is generated.

![image](https://user-images.githubusercontent.com/3043885/121251757-9ae38000-c87d-11eb-8d4d-91d5941c0ad3.png)
 

## Expected Results

Only 1 device id by device for same user

## Code Sample

 RealmUser = await RealmApp.LogInAsync(Credentials.EmailPassword(mail, pwd));

await RealmUser.LogOutAsync();

 RealmUser = await RealmApp.LogInAsync(Credentials.EmailPassword(mail, pwd)); /* new device id generated */

## Version of Realm and Tooling

- Flavor:
  - [X ] MongoDB Realm
- Client SDK Version: ? 10.2.0-beta2 and 10.1.4
- Client OS & Version: ? Xamarin Forms 5 , UWP and Android.

**Comment by carbonete** [comment] 2021-07-01 16:24
Any news ? thks

**Comment by nirinchev** [comment] 2021-07-01 18:08
No update yet, sorry. I'll ping the cloud team again.

**Comment by nirinchev** [comment] 2021-07-07 22:39
Unfortunately, this behavior is by design at the moment, but we can see how it's counter intuitive and will look to improve the experience with a future release. Since this work is outside the scope of the .NET SDK, I'll close this issue and create an internal one for the cloud team to track the improvement request.

**Closed by nirinchev** 2021-07-07 22:39 UTC
Labels: O-Community
