### ISSUE TITLE
Realm.DeleteRealm(config) intermittenlty fails

### ISSUE THREAD

**Issue by pmahend1** [realm/realm-dotnet#1781] opened 2018-10-19 19:28 UTC
## Goals
Realm.DeleteRealm(config) intermittenlty fails 
Trying to delete current ream database files that the app uses after closing the realm instances. 

## Expected Results
Should delete realm files,  Since ```IsInTransaction``` is false.

### Feature Request
Since ```DeleteRealm``` have return type void , is it possible to have a new method or extend this to return ```bool```

## Actual Results
```Exception : Unable to delete Realm because it is still open```

## Steps to Reproduce
Steps

* Get current instance from singleton class 
* Store it in class local variable - ```realmInstance```
* Dispose/Close the instance (I made sure I used Dispose on both local config and the one with singleton)
* Call Realm.DeleteRealm(config)

## Code Sample
[RealmSingleton.cs](https://gist.github.com/pmahend1/fa6fb9caad827ca9c71055c0fef5f85c)

```
realmInstance = RealmSingleton.Instance.RealmSingletonInstance;

//other stuff
if (!realmInstance.IsClosed)
{
        realmInstance.Dispose();
}


if (!RealmSingleton.Instance.RealmSingletonInstance.IsClosed)
{
        RealmSingleton.Instance.RealmSingletonInstance.Dispose();
}
if (realmInstance.IsClosed && RealmSingleton.Instance.RealmSingletonInstance.IsClosed)
{
        try
        {
                Realm.DeleteRealm(RealmSingleton.Instance?.RealmSingletonInstance?.Config);
        }
        catch (Exception e3)
        {

                Debug.WriteLine("Unable to delete realm." + e3.StackTrace);
        }

}
```

## Version of Realm and Tooling
Visual Studio 15.8.7
Xamarin Forms 3.3.x
Realm Nuget 3.2.1

* Realm Object Server Version: ?
* Flavor:
  * [x] Developer
  * [ ] Professional
  * [ ] Enterprise
* Server OS & Version: ? (e.g. CentOS 6) - NA - database product
* Client SDK Version: ? - Realm Nuget 3.2.1
* Client OS & Version: ? - Running on Android

**Comment by nirinchev** [comment] 2020-08-26 20:23
Closing as a duplicate of https://github.com/realm/realm-dotnet/issues/1773.

**Closed by nirinchev** 2020-08-26 20:23 UTC
Labels: O-Community, Reproduction-Required
