### ISSUE TITLE
Removing an item is causing a StackOverflowException

### ISSUE THREAD

**Issue by ghost** [realm/realm-dotnet#1551] opened 2017-09-12 09:57 UTC
Before I'm starting with the issue, first of all, I want to say: thank you! Realm has brought me into the world of reactive programming and I got used to it very fast, even if I came from the SQLite thinking.

## Goals
In my app, users can create an item which creation is fully done on an external server. To provide a clear indicator while the user is offline, I'm creating a placeholder which provides enough information for the user.
When the final item is available, the placeholder is going to be removed and the new item is added.

## Expected Results

    // Remove the placeholder and add the newParentItem
    db = Realm.GetInstance();
    db.Write(() =>
    {
        db.Remove(placeholderParentItem);
        db.Add(newParentItem);
    });

When executing the above code I expect that the `placeholderParentItem` is removed from the database while the `newParentItem` is added.

## Actual Results

The line `db.Remove(placeholderParentItem);` caused an `StackOverflowException`.

## Steps to Reproduce

Load the code sample, compile it and press the button twice. Pressing it once executes the desired behavior, pressing it twice causes an `StackOverflowException`.

## Code Sample

You can find a [sample project here](https://github.com/jlnostr/realm-stackoverflow-exception), the relevant code is [here](https://github.com/jlnostr/realm-stackoverflow-exception/blob/master/realm-stackoverflow-exception/MainPage.xaml.cs#L38-L79).

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: n.a.
- Client SDK Version: 1.6.0 (Xamarin, used on UWP)
- Client OS & Version: Windows 10, version 1703

**Comment by nirinchev** [comment] 2017-09-13 22:04
Thanks for the report and the kind words! I haven't been able to reproduce the exception when running on x64 windows locally. I do notice that the UI freezes and I have to kill the app. My initial bet is that it is caused by some pathological case when calculating change notifications. While we investigate, I have tried separating the adding and removing of the item in two transactions and it seems to have worked:

```csharp
db.Write(() => db.Remove(placeholderParentItem));
db.Write(() => db.Add(newParentItem));
```

**Comment by jlnostr** [comment] 2017-09-14 20:05
> Thanks for the report and the kind words!

You're welcome :)

> While we investigate, I have tried separating the adding and removing of the item in two transactions and it seems to have worked.

It works perfectly! I'm going to ask my past self why it didn't come up with this idea by itself :wink:

**Comment by papafe** [comment] 2023-11-09 10:32
I'm closing this as it's quite old and we didn't receive any similar report recently, so hopefully this has been fixed in the meanwhile. Feel free to reopen this if you still have this issue though!

**Closed by papafe** 2023-11-09 10:32 UTC
Labels: T-Bug-Crash, O-Community
