### ISSUE TITLE
Issue occurs in 2.1 version. I had to go back to 1.1.1 to overcome this. Tried 1.6 as well but it had the same issue.

### ISSUE THREAD

**Issue by sankranti2018** [realm/realm-dotnet#1682] opened 2018-02-02 15:48 UTC
## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

**Comment by nirinchev** [comment] 2018-02-02 18:43
That doesn't really give us any information, please update the issue description to explain what the problem is.

**Comment by vaddanki** [comment] 2018-02-02 19:22
I did not realise the original comments on the post are not preserved. Was referring to this thread.
https://github.com/realm/realm-dotnet/issues/1271
I am using nuget to add Realms package to my project. With 2.10 version I get a message that librealm-wrappers.a is not found. When building for IOS, I see an error from MTouch that Realm.dll cannot be loaded even though the dill is present at the location pointed out in the error message. I had to revert back to 1.1 version and everything works well. I like the Realm package a lot when compared to sqlite. So , I would like to follow closely on your advise. Feel free to let me know if there is anything else you need from me. I am using the latest version of Visual Studio (2017 Preview) and generally update all packages as they become available. Thank you.

**Comment by nirinchev** [comment] 2020-08-26 20:54
Closing this as it concerns a very old version of the library.

**Closed by nirinchev** 2020-08-26 20:54 UTC
Labels: O-Community, T-Bug
