### ISSUE TITLE
Realm nuget version 4.2.0 disables breakpoints in Xamarin.iOS project in Visual Studio for Mac

### ISSUE THREAD

**Issue by iviich4eL** [realm/realm-dotnet#1916] opened 2019-10-21 10:20 UTC
Debugger does not hit any breakpoint in Xamarin.ios app on startup but in shared .net standard 2.0 project everything is ok.

iOS build options:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/29166300/67197347-41f37980-f405-11e9-9b53-32874e088d9a.png">

Visual Studio Mac version: 8.3.4 (build 8)

**Comment by nirinchev** [comment] 2019-10-21 12:59
Duplicate of https://github.com/realm/realm-dotnet/issues/1910

**Closed by nirinchev** 2019-10-21 12:59 UTC
Labels: O-Community
