### ISSUE TITLE
Unhandled Exception:  System.NullReferenceException: Object reference not set to an instance of an object. occurred Realm 1.5.0

### ISSUE THREAD

**Issue by deanilvincent** [realm/realm-dotnet#1491] opened 2017-07-25 14:08 UTC
I'm having a problem with realmdb for Xamarin.Forms.

![testing1](https://user-images.githubusercontent.com/10904957/28575900-e1c5281a-7184-11e7-9d50-b6e161190634.PNG)

It says, "System.NullReferenceException: Object reference not set to an instance of an object."

Here's my model: 

```
using Realms;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyProject.Models
{
    public class Reminders : RealmObject
    {
        [PrimaryKey]
        public int MyId { get; set; }

        public string Name { get; set; }

        public string Desc { get; set; }
    }
}
```
Problem persists on Android and iOS.

I created a blog here:
https://deanilvincent.github.io/2017/06/09/creating-simple-xamarin-forms-crud-app-with-realmdb-and-mvvm-part1/
where I did it working last June. But now, I'm having a problem. Same codes, same logic but I don't know why I got this null error thing which I really didn't expect. Thank you in advance :)

**Comment by nirinchev** [comment] 2017-07-25 16:36
That is surprising indeed. Do you think you can zip your project and send it over so we can check it out?

**Comment by deanilvincent** [comment] 2017-07-25 21:46
Sure I can send it to you

**Comment by nirinchev** [comment] 2017-07-25 21:56
If it's sensitive, you can email it to help@realm.io, otherwise, feel free to drop it in this issue.

**Comment by deanilvincent** [comment] 2017-07-26 07:13
I've already sent the link of my onedrive containing the project. :) Thank you and I'm looking forward to you response soon :)

**Comment by nirinchev** [comment] 2017-07-26 07:46
Hi, the problem is that `_reminders` is null - it appears it is never assigned to.

**Comment by deanilvincent** [comment] 2017-07-26 08:27
@nirinchev  have you received my attached file? Ahm it's my private variable and used inside the public get set of Reminders

**Comment by deanilvincent** [comment] 2017-07-26 08:47
yeah @nirinchev I also did some breakpoints on that line yesterday and it always return a null value. I usually use full property in some of my mobile app projects so I got no idea why it returns a null now. Another thing is, I also did that approach in my blog tutorials and I got it working that time. But now, I wonder why it returns a null value :(

**Comment by nirinchev** [comment] 2017-07-26 08:55
In section 7.1 of your blog post you have
```csharp
private CustomerDetails _customerDetails = new CustomerDetails();
```

In your current project, you never assign the field, which is why it's null.

**Comment by deanilvincent** [comment] 2017-07-26 08:57
Ohhh Haha wait wait let me check on my current project. Yeah, I think that's the problem since I didn't instantiate it inside my view model :)

**Comment by deanilvincent** [comment] 2017-07-26 09:05
It has a value now. Thank you for the hint. I missed out something that I have to instantiate it :)

**Closed** 2017-07-26 09:05 UTC
