### ISSUE TITLE
Incorrect Subscriptions.State

### ISSUE THREAD

**Issue by movsar** [realm/realm-dotnet#3180] opened 2023-01-18 03:08 UTC
### What happened?

[realm.Subscriptions.State ](url)is set to Complete even when the network is down

### Repro steps

After getting a realm instance, log `realm.Subscriptions.State` while network is down.

### Version

.NET 6

### What Atlas Services are you using?

Atlas Device Sync

### What type of application is this?

Other

### Client OS and version

Windows 10

**Comment by nirinchev** [comment] 2023-01-18 03:29
Can you share the exact code you're using? Generally speaking, the state would be complete if:
1. You don't have any subscriptions - e.g. you open the Realm and immediately check the subscription state. Since there's no data that needs to be synchronized, the subscription state is "Complete".
2. You have previously synchronized with the server and the server is doing "steady state synchronization" - i.e. it has sent the initial batch of data that matched your subscriptions and is only sending incremental changes now.

If your use case falls under any of these cases, then this is the expected behavior.

**Comment by movsar** [comment] 2023-01-27 12:03
@nirinchev I open the database with the following config:
```
new FlexibleSyncConfiguration(appUser, FileService.DatabasePath)
            {
                SchemaVersion = 1,
                PopulateInitialSubscriptions = (realm) =>
                {
                    Debug.WriteLine($"APP: Realm : PopulateInitialSubscriptions");

                    realm.Subscriptions.Add(realm.All<Entities.Entry>());
                    realm.Subscriptions.Add(realm.All<Entities.Language>());
                    realm.Subscriptions.Add(realm.All<Entities.Phrase>());
                    realm.Subscriptions.Add(realm.All<Entities.Source>());
                    realm.Subscriptions.Add(realm.All<Entities.Translation>());
                    realm.Subscriptions.Add(realm.All<Entities.User>());
                    realm.Subscriptions.Add(realm.All<Entities.Word>());
                }
            };
```

as you can see, I have Subscriptions, and considering that the use case I reported is observed even on network loss, there is absolutely no way for realm to ascertain that the sync is complete, it has to connect to server to do that.

**Comment by nirinchev** [comment] 2023-01-27 12:59
There are two things to consider here:
1. `PopulateInitialSubscriptions` is only invoked once - i.e. when the Realm has been created. Is it possible that you created the Realm file before adding those subscriptions? Easiest way to check this would be to inspect `realm.Subscriptions` and check if their number matches your expectations.
2. There are two phases of synchronization when using Flexible Sync. First is the bootstrap phase, which occurs after you update your subscriptions. The server will send back all documents that match the requested subscriptions at the time the subscription update was received. Once that is done, we move on to steady-state synchronization, which sends data back and forth as it comes. The `Complete` state pertains only the first phase - i.e. the bootstrap phase. Once it is complete, the subscription set is marked as `Complete` and it'll remain like this until you change the subscriptions. This is why even if you're offline, you can get `Complete` there.

**Comment by movsar** [comment] 2023-01-27 15:18
#The Complete state pertains only the first phase - i.e. the bootstrap phase. Once it is complete, the subscription set is marked as Complete and it'll remain like this until you change the subscriptions. This is why even if you're offline, you can get Complete there.

That's interesting, yes, this is exactly the case, but that's not what I would expect from that method, because my app subscribes to essentially all of the entities with `PopulateInitialSubscription`, and I expected that `WaitForSynchronization() `would wait when any of the **items** in these subscriptions change, not subscriptions themselves as I don't need to change them if they include all objects, right?

So, in my case, there is no way to wait for the changes, is there? Or should I use `SyncSession's WaitForDownload()` instead?

**Comment by nirinchev** [comment] 2023-01-27 16:29
Correct - if a subscription is in a `Complete` state but you want to ensure that you have the absolute latest state from the server, you need to call `realm.SyncSession.WaitForDownload`.

**Comment by movsar** [comment] 2023-01-30 09:58
@nirinchev Is this also by design? That SyncSession is Active despite being in the Airplane mode?
![image](https://user-images.githubusercontent.com/18250365/215445619-47d6e8aa-4ec8-4ebc-b3de-abe722ac06bc.png)

**Comment by nirinchev** [comment] 2023-01-30 10:00
Yes, the session state indicates where the session is attempting to communicate with the server. You are probably looking for ConnectionState which should indicate whether there's connection to the server.

**Closed** 2023-01-30 11:57 UTC
Labels: T-Bug, O-Community, SDK-Use:Sync, App-type:Other
