### ISSUE TITLE
[Bug]: After the Upgrade 10.18.0 - Crash Occured using Binding RealmObject on Xaml Page

### ISSUE THREAD

**Issue by Engincode** [realm/realm-dotnet#3086] opened 2022-11-10 13:56 UTC
### What happened?

We upgraded Realm-Dotnet from 10.17.0. to 10.18.0.
After the upgrade some xaml pages doesn't work.
We found the main reason;
When we use a Binding Property in a class that inherits from RealmObject errror is occuring.

Example:
**Customer.cs** (inherits from RealmObject)
![image](https://user-images.githubusercontent.com/12773298/201109434-d5f3b63d-0b50-431f-ad9c-49f2e2758d17.png)

**Xaml Page**
![image](https://user-images.githubusercontent.com/12773298/201109894-42dbfca8-a52f-43da-8eeb-b5e972de494c.png)

When the page opening
Example Error Message (Android or iOS) doesn't matter.

	0x49 in Realms.DataBinding.RealmObjectTypeDelegator.GetPropertyImpl at D:\a\realm-dotnet\realm-dotnet\Realm\Realm\DataBinding\RealmObjectTypeDelegator.cs:48,13	C#
 ............

### Repro steps

Crash.

### Version

.NET Standart 2.1

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Xamarin

### Client OS and version

10.18.0.

### Stacktrace of the exception/crash you're getting

```shell
0x49 in Realms.DataBinding.RealmObjectTypeDelegator.GetPropertyImpl at D:\a\realm-dotnet\realm-dotnet\Realm\Realm\DataBinding\RealmObjectTypeDelegator.cs:48,13	C#
```

**Comment by meierhoeferjannis** [comment] 2022-11-16 14:55
Could the Problem be that he is using Compiled Bindings for the DataTemplate and Realm is doing some Black magic in the background?. 
See also #2270

**Comment by papafe** [comment] 2022-11-16 14:59
Hi @Engincode,
Could you show how you're setting up your ViewModel and initialising the bindings?

**Comment by Engincode** [comment] 2022-11-16 17:08
@papafe First of all, we were not getting any errors when we upgraded to Realm before.
We got it in the **last version.**
When you switch to the previous library; it doesn't give an error.
I shared the code sample.
What detail do you need?

**Comment by papafe** [comment] 2022-11-16 19:06
@Engincode Version 10.18.0 introduced support for source generated models, so there has been quite a lot of changes to the Realm code internally. 
It would be good to see how you initialise the bindings in your ViewModel, so it would be easier to understand what is the source of the issue. I have a feeling that this could be happening when an unmanaged object (an object that has not been added to Realm yet) is used in bindings, similarly to another reported issue. This could also be something different, so it would be good to know how you are using the Realm object in the view model

**Comment by Engincode** [comment] 2022-11-17 11:47
@papafe 
I don't understand what part of the code you want exactly?
When calling a new page, we send a view model in the constructor method.
Classic code.
Then we use Property in ViewModel on Xaml Page.
We're getting an error on the latest version Realm.

**Comment by papafe** [comment] 2022-11-17 12:21
@Engincode It would be useful to see how does your `ViewModel` class looks like, to see how you're setting the binding for the Customers collection. 
I think this could be the same as #3094, where it happens when using unmanaged objects. If you can show how you set the bindings, or confirm yourself you are using unmanaged objects when it happens, then I would be sure this is caused by the same bug.

**Comment by Engincode** [comment] 2022-11-17 13:09
@papafe 
CustomerListPage.xaml.cs

	public CustomerListPage()
	{
		CustomerListPageViewModel myModel = new CustomerListPageViewModel();
		myModel.CustomerList = new List<CustomerPageViewModel>();
		myModel.CustomerList.Add(new Customer() { Id = 12, BrandName = "DupplerxCo"});
		
		BindingContext = myModel;

		InitializeComponent();

		Init();
	}
	
CustomerListPageViewModel.cs	

	List<CustomerPageViewModel> _customerList;
	public List<CustomerPageViewModel> CustomerList
	{
		get => _customerList;
		set => SetProperty(ref _customerList, value);
	}
	
CustomerPageViewModel.cs	
	public string BrandName => Customer?.BrandName;

**Comment by papafe** [comment] 2022-11-17 13:34
@Engincode As I suspected this is the same as #3094 and will be fixed with PR #3097

As I have also suggested in #3094, you could consider using Realm object and collections directly in bindings, without the need to create other collections. For instance:

```csharp
public class CustomerListPageViewModel
{
    private Realm realm;

    private IQueryable<Customer> CustomerList { get; } //Need to bind to this in the XAML file

	public CustomerListPageViewModel()
	{
        realm = Realm.GetInstance();
        CustomerList = realm.All<Customer>();
	}

    public AddCustomer()
    {
        realm.Write(() => 
        {
            realm.Add(new Customer { Id = 23, Brandname = "MyBrand"});
        })
    }
}
```
*(I wrote this off the top of my head, so something could be wrong, but I hope you get the idea)*

This is what we recommend to developers, as it is the most idiomatic way to use Realm, so you don't need to worry about keeping both collections and the db updated, or worry about notifications. With this approach you simply update the database and then the UI will be updated accordingly.

**Comment by Engincode** [comment] 2022-11-17 15:04
@papafe 
Why am I making so many changes to the code?
Why am I doing code changes with Realm objects?
Do you plan to fix this error yourside?

**Comment by papafe** [comment] 2022-11-17 15:22
@Engincode this specific bug will be fixed by us with PR #3097.
You don't need to make changes to your code, but I what I was showing is the recommended approach to use Realm with bindings in Xamarin/MAUI and so on. You are not forced to follow that approach, but in general it helps in simplifying the code quite a lot.

**Comment by Engincode** [comment] 2022-11-17 15:56
@papafe  The code I shared was an example. (not a really code)
Our project ; operations in Realm object  already done with "Realm.Write" scope.
Now 
Are we wait the new version on Realm?

**Comment by papafe** [comment] 2022-11-18 07:35
@Engincode yes, the fix will be included in the next version of Realm

**Comment by Engincode** [comment] 2022-11-18 18:44
@papafe  Thanks.

**Closed** 2023-01-12 14:53 UTC
Labels: O-Community
