### ISSUE TITLE
Realm Sync creating incomplete documents

### ISSUE THREAD

**Issue by mphill** [realm/realm-dotnet#2314] opened 2021-03-29 21:30 UTC
## Goals

Sync a Xamarin Forms app to Realm/Atlas

## Expected Results

When saving:

```
public class Person : RealmObject {
   [PrimaryKey]
   [MapTo("_id")]
   public ObjectId Id { get; set; } = ObjectId.GenerateNewId();

   public string Name { get; set;} = "Full name"
   public int Count { get; set;} ;
   public bool Enabled { get; set;} 
}
```

I would expect that **all** properties show up in Atlas

## Actual Results

Data will sync, but any value that is equal to the `default` i.e.:
```
public bool Enabled { get; set;} = false;
public int Count { get; set;} = 0;
```

Does not show up in Atlas - the properties are simply missing. 

In the example above, the resulting document would be.

```
{
 "Name" : "Full Name"
}
```
_**`Count` and `Enabled` are now missing**_

Note:
enums that are mapped to a raw type (like int) that are equal to 0 also fail to sync properly too. The properties in some cases are marked as **mandatory** and the property is still missing!

Incomplete documents are created that are in an inconsistent state. As a result sync starts to break when making schema changes or even trying to edit objects directly via the realmdb web interface.

## Steps to Reproduce

Create a simple class:

```
public class Person : RealmObject {
   [PrimaryKey]
   [MapTo("_id")]
   public ObjectId Id { get; set; } = ObjectId.GenerateNewId();

   public string Name { get; set;} = "Full name"
   public int Count { get; set;} ;
   public bool Enabled { get; set;} 
}
```

Create a Realm Sync App and define a schema for this object
Turn on Realm Sync.
Create a simple client App that connect to Sync Realm and create the object :

Atlas Result:
```
{
 "_id" : ObjectId
 "Name" : "Full Name"
}
```

This issue is happening in the Swift SDK as well

https://github.com/realm/realm-cocoa/issues/7192

## Version of Realm and Tooling

- Flavor:
  - [X] Realm Cloud
  - [ ] Self-Hosted

- Client SDK Version:  10.1.2
- Client OS & Version: iOS/Android

**Comment by nirinchev** [comment] 2021-03-29 23:58
This is a duplicate of https://github.com/realm/realm-dotnet/issues/2165. We're working on a fix server-side, but we don't have an estimate yet. I'll close this issue and we'll update the other one once we have something available.

**Closed by nirinchev** 2021-03-29 23:58 UTC
Labels: O-Community
