### ISSUE TITLE
Realm doesn't seem to recognize F# properties

### ISSUE THREAD

**Issue by willsb** [realm/realm-dotnet#1550] opened 2017-09-11 23:13 UTC
## Goals
Use Realm on a F# PCL, consumed by an iOS app.

## Expected Results
Inheriting from `RealmObject` makes makes Fody weave the properties that have getters and setters so I can use Realm normally throughout the project

## Actual Results

I get an error saying that my properties are not being persisted. 
![image](https://user-images.githubusercontent.com/7688727/30300760-d30ce2f4-972c-11e7-9cac-b50cfcb4bd7a.png)

## Steps to Reproduce

Simply create a new F# project and add Realm to it. When trying to compile, Fody/RealmWeaver will display the errors. 

## Code Sample
A set up project can be found [here](https://github.com/willsb/EnPassant/tree/realm-issue)

## Version of Realm and Tooling

- Realm Object Server Version: Not applicable
- Flavor:
  - [X] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: Not applicable
- Client SDK Version: 1.6.0
- Client OS & Version: iOS 10.3 (though error happens when compiling the PCL)

**Comment by nirinchev** [comment] 2017-09-13 21:43
Thank you for your report. My guess would be that F# properties generate different IL which is confusing our weaver. While we don't officially support F#, we could try and see if it'll be easy to do so.

**Comment by willsb** [comment] 2017-10-20 15:14
So I created two very simple classes in both C# and F# to check what the differences in IL generation are.

F#:
```fsharp
namespace Realm.FSharp

type MyClass() = 
    member val Id = 0 with get, set
```

C#:
```csharp
namespace RealmTest.CSharp
{
    public class MyClass
    {
        public int Id { get; set; }
    }
}
```

A diff of the generated IL can be seen [here](https://www.diffchecker.com/3oTAsyZt).

Seems like the only differences are the names of the backing fields (`<Id>k__BackingField` in C# and `Id@` in F#). 
Checking the method that's responsible for [getting the backing field](https://github.com/realm/realm-dotnet/blob/9f002e5e588a110a628f30d91ffdb043e6233fd0/Weaver/RealmWeaver.Fody/extensions/PropertyDefinitionExtensions.cs#L102-L109), there apparently are no problems, for both compilers generate the `ldfld` instruction. 

The only difference between the get methods is that the F# version begins with a `nop` (something that also doesn't seem to be a problem).

**Comment by nirinchev** [comment] 2018-06-22 12:13
This is a duplicate of https://github.com/realm/realm-dotnet/issues/1691.

**Closed by nirinchev** 2018-06-22 12:13 UTC
Labels: O:User, T:Enhancement
