### ISSUE TITLE
[Bug]: Can't cancel a non-existing write transaction

### ISSUE THREAD

**Issue by sansamit** [realm/realm-dotnet#3095] opened 2022-11-15 06:57 UTC
### What happened?

15:26:23.709: E Can't cancel a non-existing write transaction
15:26:23.709: E    at Realms.NativeException.ThrowIfNecessary(Func`2 overrider)
   at Realms.SharedRealmHandle.CancelTransaction()
   at Realms.Transaction.Rollback()
   at Realms.Transaction.Dispose()
   at Realms.Realm.Write[T](Func`1 function)
   at Realms.Realm.WriteAsync[T](Func`1 function, CancellationToken cancellationToken)
   at Superhare.NHFutures.Threading.Activities.NHFuturesFuCodeSubscriber.<>c__DisplayClass7_0.<<OnSubscribe>b__0>d.MoveNext() in E:\Clients\__\__\__\__\__\__\__\__.cs:line 166
15:26:27.416: E MapViewOfFileFromApp() failed: Exec format error size: 49283072 offset: 0
15:26:27.416: E    at Realms.RealmConfiguration.CreateHandle(RealmSchema schema)
   at Realms.RealmConfiguration.CreateHandleAsync(RealmSchema schema, CancellationToken cancellationToken)
   at Realms.RealmConfigurationBase.CreateRealmAsync(CancellationToken cancellationToken)
   at Superhare.NHFutures.Threading.Activities.NHFuturesFuCodeSubscriber.<>c__DisplayClass7_0.<<OnSubscribe>b__0>d.MoveNext() in E:\Clients\__\__\__\__\__\__\__\__.cs:line 157

*** __ => Named '__' processed

### Repro steps

Since it is intermittent, it is almost impossible to reproduce.

### Version

Net6

### What SDK flavour are you using?

Local Database only

### What type of application is this?

WPF

### Client OS and version

Windows 10 Pro 19044.2251

### Code snippets

await realm.WriteAsync

### Stacktrace of the exception/crash you're getting

```shell
15:26:23.709: E Can't cancel a non-existing write transaction
15:26:23.709: E    at Realms.NativeException.ThrowIfNecessary(Func`2 overrider)
   at Realms.SharedRealmHandle.CancelTransaction()
   at Realms.Transaction.Rollback()
   at Realms.Transaction.Dispose()
   at Realms.Realm.Write[T](Func`1 function)
   at Realms.Realm.WriteAsync[T](Func`1 function, CancellationToken cancellationToken)
   at Superhare.NHFutures.Threading.Activities.NHFuturesFuCodeSubscriber.<>c__DisplayClass7_0.<<OnSubscribe>b__0>d.MoveNext() in E:\Clients\__\__\__\__\__\__\__\__.cs:line 166
15:26:27.416: E MapViewOfFileFromApp() failed: Exec format error size: 49283072 offset: 0
15:26:27.416: E    at Realms.RealmConfiguration.CreateHandle(RealmSchema schema)
   at Realms.RealmConfiguration.CreateHandleAsync(RealmSchema schema, CancellationToken cancellationToken)
   at Realms.RealmConfigurationBase.CreateRealmAsync(CancellationToken cancellationToken)
   at Superhare.NHFutures.Threading.Activities.NHFuturesFuCodeSubscriber.<>c__DisplayClass7_0.<<OnSubscribe>b__0>d.MoveNext() in E:\Clients\__\__\__\__\__\__\__\__.cs:line 157


*** __ => Named '__' processed
```

**Comment by sansamit** [comment] 2022-11-17 01:54
I've spent almost 2 weeks on this issue,
As a result, it seems to have reached an almost definite suspicion.

This is closely related to Realm Studio 12.0.

Since the program I developed only collects data, I don't know how the data is being accumulated (it hasn't been developed yet), so I had no choice but to test Realm Studio 12.0 in parallel.

by chance now!!
Realm Studio 12.0 is running without opening the realm db file being collected... Surprisingly, no error occurs.

Of course, time is still running out. So check some more
A definitive conclusion must be drawn.

It's hard to understand that just by running the Realm Studio 12.0 program and opening the realm file, it affects my program.
It's amazing.

**Comment by sansamit** [comment] 2022-11-17 08:13
I've been testing this and that all day today.

It doesn't seem to be a problem with realm studio either.
Because, by creating another app and opening a local file in the same location, the same error occurred during real-time monitoring.

Is a realm's local file dedicated to a single program?
Can't more than one program access the same local database file?

**Comment by nirinchev** [comment] 2022-11-17 10:28
Looking at the stacktrace, there are few interesting things:

1. You're using `WriteAsync`, but that appears to be calling `Write`. This means that you're doing that on a thread that doesn't have a synchronization context. It's not a problem as the SDK will fallback to the synchronous write, but it may be pointing to some wrong assumptions on your end.
2. The transaction is getting rolled back rather than committed. Typically the reason for this is that the lambda provided to `Realm.Write` throws an exception. This should work correctly, but perhaps there's a weird interaction when another process is interacting with the Realm file. I'll try to reproduce it, but in the meantime you can try and wrap your write code in a try-catch block and see if it's indeed throwing an exception. Knowing the exception being thrown will likely point us to the root cause of the bug.

As for multiprocess support - that should indeed work, but there may be a bug that needs to be addressed.

**Comment by sansamit** [comment] 2022-11-18 09:00
WriteAsync, but Write is because WriteAsync is called in Task.Run, and SynchronizedContext is null, so Write is supposed to be called. I understand this.

The problem is, it said that there would be an error about the phenomenon of rollback without committing in paragraph 2, but there is a way to check it. There is a try-catch, but only the above error is output.

**Comment by nirinchev** [comment] 2022-11-18 11:55
Can you share the code that is throwing?

**Closed** 2023-01-05 18:09 UTC
Labels: O-Community, More-information-needed, Waiting-For-Reporter
