### ISSUE TITLE
iOS Crash on Realm Compact

### ISSUE THREAD

**Issue by stevedcc** [realm/realm-dotnet#3428] opened 2023-08-30 12:12 UTC
### What happened?

A user experienced an app crash and sent the iOS Logs.  The logs appear to suggest that the crash occurred during Realm compaction

```
0   libsystem_kernel.dylib        	       0x1e03891a0 __fcntl + 8
1   libsystem_kernel.dylib        	       0x1e0388880 fcntl + 88
2   realm-wrappers                	       0x10301673c realm::util::File::sync() + 32
3   realm-wrappers                	       0x102f0fa54 realm::DB::compact(bool, std::__1::optional<char const*>) + 512
4   realm-wrappers                	       0x102cf06e8 realm::_impl::RealmCoordinator::open_db() + 1736
5   realm-wrappers                	       0x102cf1444 realm::_impl::RealmCoordinator::do_get_realm(realm::RealmConfig&&, std::__1::shared_ptr<realm::Realm>&, std::__1::optional<realm::VersionID>, realm::util::CheckedUniqueLock&) + 72
6   realm-wrappers                	       0x102cf1330 realm::_impl::RealmCoordinator::get_realm(realm::RealmConfig, std::__1::optional<realm::VersionID>) + 480
7   realm-wrappers                	       0x102d69a0c realm::Realm::get_shared_realm(realm::RealmConfig) + 120
8   realm-wrappers                	       0x102ca4cfc shared_realm_open + 868
```

### Repro steps

1. Open App
2. Crash

### Version

10.20.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Xamarin

### Client OS and version

iOS 16.6

### Stacktrace of the exception/crash you're getting

```shell
0   libsystem_kernel.dylib        	       0x1e03891a0 __fcntl + 8
1   libsystem_kernel.dylib        	       0x1e0388880 fcntl + 88
2   realm-wrappers                	       0x10301673c realm::util::File::sync() + 32
3   realm-wrappers                	       0x102f0fa54 realm::DB::compact(bool, std::__1::optional<char const*>) + 512
4   realm-wrappers                	       0x102cf06e8 realm::_impl::RealmCoordinator::open_db() + 1736
5   realm-wrappers                	       0x102cf1444 realm::_impl::RealmCoordinator::do_get_realm(realm::RealmConfig&&, std::__1::shared_ptr<realm::Realm>&, std::__1::optional<realm::VersionID>, realm::util::CheckedUniqueLock&) + 72
6   realm-wrappers                	       0x102cf1330 realm::_impl::RealmCoordinator::get_realm(realm::RealmConfig, std::__1::optional<realm::VersionID>) + 480
7   realm-wrappers                	       0x102d69a0c realm::Realm::get_shared_realm(realm::RealmConfig) + 120
8   realm-wrappers                	       0x102ca4cfc shared_realm_open + 868
```

**Comment by nirinchev** [comment] 2023-08-30 12:28
This is likely related to https://github.com/realm/realm-core/issues/6813. If you are able to reproduce this, that would be super helpful, otherwise we'll keep trying to get to the root cause.

I'll close this issue to consolidate discussion in the Core ticket.

**Closed by nirinchev** 2023-08-30 12:28 UTC
Labels: T-Bug, O-Community, SDK-Use:Local, App-type:Xamarin
