### ISSUE TITLE
MAUI support

### ISSUE THREAD

**Issue by pikausp** [realm/realm-dotnet#3144] opened 2023-01-02 14:55 UTC
Hello,

We are currently upgrading our quite outdated mobile app and bringing it from Xamarin.Forms over to MAUI. The changelog states that preview support for MAUI was added.

How stable is the current version of Realm when it comes to iOS/Android MAUI workloads and if not yet production ready is there any ETA for when it might be?

Thank you

**Comment by nirinchev** [comment] 2023-01-03 01:24
It's stable when it comes to production usage. There are some features that are poorly or completely unsupported though. The two main ones are:
- Hot reload on iOS: the issue is that hot reload enabled apps don't support native libraries so Realm can't work in that mode.
- Support for automatic transactions in compiled databindings: due to the way compiled bindings work, we can't use our usual tricks to detect a change is coming from the UI and automatically start and commit a write transaction. This means that if you want to have two-way data bindings, you either need to ensure a transaction is opened before changes from the UI occur or use the classic bindings instead.

**Comment by 420tech** [comment] 2023-01-05 20:47
I am able to run a simple "ToDo" app on Android, iOS and Mac. On Windows, the app never loads. Is this a known issue?

**Comment by nirinchev** [comment] 2023-01-05 21:02
Does the app work on Windows without Realm? I've tried running MAUI tests on Windows and that seems to work, although the tooling is quite unstable and I couldn't get the app to run without being launched by VS (that's the case for an empty MAUI app without Realm).

**Comment by nirinchev** [comment] 2023-01-05 21:56
Can you share the project you're trying to run? That way I can give it a go locally and see what's going wrong.

**Comment by 420tech** [comment] 2023-01-05 22:31
https://github.com/rsteinbakk/TodoMaui-FullStack-MongoDB.

**Comment by nirinchev** [comment] 2023-01-05 22:52
The issue you're seeing appears to be caused by the frames wrapping the entries in your login page: https://github.com/rsteinbakk/TodoMaui-FullStack-MongoDB/blob/be7f0a8ac35af0f3bf5fbefca86a99142ad20497/TodoMaui/Views/LoginPage.xaml#L14-L19.

If I move the entries outside the frames the app launches successfully - your page should look something like this:

```xml
        <VerticalStackLayout Spacing="25" Padding="30, 0" VerticalOptions="Center">
            <Image Source="todologo.svg" Margin="0, 0, 0, 15"/>
            <Entry Placeholder="Email" Text="{Binding EmailText}" TextColor="#333"/>
            <Entry Placeholder="Password" IsPassword="True" Text="{Binding PasswordText}" TextColor="#333"/>
            <Button Text="Login" Command="{Binding LoginCommand}"/>
            <Button Text="Create Account" Background="Transparent" TextColor="#EEE" Command="{Binding CreateAccountCommand}"/>
        </VerticalStackLayout>
```

I'm not a MAUI expert, so cannot say why the frames are causing the layout engine to freeze up (while debugging, it appears to get stuck in `MeasureOverride`), but I'm fairly confident this is not a Realm issue as that's happening before the first call into Realm API.

**Comment by 420tech** [comment] 2023-01-05 23:04
Thank you! The weird thing is the layout for that login page has been used a LOT - its a copy/paste template I use as placeholders for this kind of thing. Never had a problem with that before.

**Comment by nirinchev** [comment] 2023-01-05 23:25
Yeah, MAUI feels a little finicky at the moment, so maybe it's just a regression that flew under the radar.

**Comment by nirinchev** [comment] 2023-01-06 01:38
I'm going to close this one - if you folks run into any issues or have further questions, feel free to reopen or file a new issue.

**Closed by nirinchev** 2023-01-06 01:38 UTC
Labels: O-Community, More-information-needed, Waiting-For-Reporter
