### ISSUE TITLE
Realm .NET Migration With Relationship

### ISSUE THREAD

**Issue by alneryus1** [realm/realm-dotnet#1976] opened 2020-04-02 00:44 UTC
## Goals
I have changed the table name and fields,
the table has relation with an other table.
i want to migrate including its relation.
What should I do?

## Code Sample
this is old table.
Lesson class has a child class called Student.
```
    public class Lesson: RealmObject
    {
        public string Subject{ get; set; }
        public IList<Student> Students{ get; }
    }
```
```
 public class Student: RealmObject
    {
        public string Name{ get; set; }
    }
```

I have changed name Lesson to SchoolLesson.
```
    public class SchoolLesson: RealmObject
    {
        public string Subject{ get; set; }
        public IList<Student> Students{ get; }
    }
```

i tried to migrate with relation.
```
        public void MigratePerson(Migration migration)
        {
            var oldRecords = migration.OldRealm.All("Lesson");

            for (var i = 0; i < oldRecords.Count(); i++)
            {
                var oldRecord = oldRecords.ElementAt(i);
                var newRecord = new SchoolLesson();

                newRecord.Subject = oldRecord.Subject;

                foreach (var student in oldRecord.Students)
                {
                    newRecord.Students.Add(student);
                }
                migration.NewRealm.Add(newRecord);
            }
        }
```
it throew exception when NewRealm.Add().
`Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: '型 'Realms.Dynamic.DynamicRealmObject' を 'xxx.Student' に変換できません'`

## Version of Realm and Tooling
Realm Version 3.2.1

**Comment by peppy** [comment] 2020-04-02 05:06
I believe the issue is that you're trying to assign the student from the previous realm schema to the new one. you may fix this by also making a new student in your inner `foreach` loop.

```csharp
        public void MigratePerson(Migration migration)
        {
            var oldRecords = migration.OldRealm.All("Lesson");

            for (var i = 0; i < oldRecords.Count(); i++)
            {
                var oldRecord = oldRecords.ElementAt(i);
                var newRecord = new SchoolLesson();

                newRecord.Subject = oldRecord.Subject;

                foreach (var student in oldRecord.Students)
                {
                    newRecord.Students.Add(new Student { Name = student.Name }); // <- construct a new student here
                }
                migration.NewRealm.Add(newRecord);
            }
        }
```

I'm basing this assumption off the (limited) migration documentation which doesn't mention being able to reassign RealmObjects from a previous instance to a new one.

**Comment by alneryus1** [comment] 2020-04-02 07:07
I understood RealmObjects can't move old schema to new one,  thanks to you.
But I faces two new problems.

1.   If a table has deep hierarchy relation,Do I need to create new instance of all children?
for example, If Students has Pets(dogs, cats...) ,
```
            foreach (var oldStudent in oldRecord.Students)
            {
                var newStundet = new Student { Name = student.Name });
                foreach (var pet in oldStudent.Pets)
                {
                    newStundet.Pets.Add(new Pet() { xxx = pet.xxx });
                }
                newRecord.Students.Add(newStundet);
            }
```
Is this  inevitable?

2. If Student has relation with an other table, it is difficult to migrate with obtaining consistency.
If Shool (RealmObject Class) has Students property too, do i have to construct Student and link "School" and "SchoolLesson"?
the same Students belong "School" and "SchoolLesson".

**Comment by peppy** [comment] 2020-04-02 07:16
If your goal is simply to rename the `Lesson` class, then I think [this](https://github.com/realm/realm-cocoa/issues/2491) issue is relevant (and still not implemented, it would seem). I don't know if there's a way around this, but migration looks to be specifically aimed at easily changing properties of classes, rather than class structure.

One method you may be able to try is keeping the old class and also the new, then doing the migration using *only* the new schema. Then you could delete the old class in a separate future migration. By doing this (and only referencing the new schema) both models would share the `Student` implementation so you should be able to assign it as you want to do, preserving all nested relations.

**Closed** 2020-06-25 20:02 UTC
Labels: O-Community
