### ISSUE TITLE
Missing callback on SubscribeForNotifications

### ISSUE THREAD

**Issue by nielsenko** [realm/realm-dotnet#1689] opened 2018-02-20 15:01 UTC
The initial callback on `SubscribeForNotifications` are sometimes missing. The following test case exercise the problem.
````
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Nito.AsyncEx;
using NUnit.Framework;
using Realms;

namespace Tests.Unit.Helpers
{
	public class Dummy : RealmObject
	{
		public IList<Dummy> Friends { get; }
	}

	public class RealmTests
	{
		[Test]
		public async Task DoubleSubscribeTest()
		{
			await new AsyncContextThread().Factory.Run(async () =>
			{
				AsyncCountdownEvent countDownEvent;
				int initCalls = 0;
				int updateCalls = 0;
				void helper(IRealmCollection<Dummy> c, ChangeSet changes, Exception ex)
				{
					if (changes == null)
						++initCalls;
					else
						++updateCalls;

					countDownEvent.TrySignal(1);
				}

				async Task waitAsync() 
				{
					var signal = countDownEvent.WaitAsync();
					await Task.WhenAny(signal, Task.Delay(1000));
				}

				var config = new RealmConfiguration("test.db");
				Realm.DeleteRealm(config);
				using (var realm = Realm.GetInstance(config))
				{
					var d = new Dummy();
					realm.Write(() => realm.Add(d));

					countDownEvent = new AsyncCountdownEvent(2);
					var s1 = d.Friends.SubscribeForNotifications(helper);
					var s2 = d.Friends.SubscribeForNotifications(helper);
					await waitAsync();
					Assert.That(initCalls, Is.EqualTo(2));

					countDownEvent = new AsyncCountdownEvent(1);
					var s3 = d.Friends.SubscribeForNotifications(helper);
					await waitAsync();
					Assert.That(initCalls, Is.EqualTo(3)); // <-- Why does this fail?!

					countDownEvent = new AsyncCountdownEvent(3);
					realm.Write(() =>
					{
						d.Friends.Add(d); // trigger the subscriptions..
					});
					await waitAsync();
					Assert.That(updateCalls, Is.EqualTo(3));

					s1.Dispose();
					s2.Dispose();
					s3.Dispose();
				}
			});
		}
	}
}
````
Basically I manage to call `SubscribeForNotifications` without `helper` getting called with `changes == null`. It happens, if there is already one or more similar subscriptions. This is a degenerate example, but it can happen in real-life, if various places in the code subscribes to the same `IRealmCollection<T>`.

This was tested with latest nightly nuget: _Realm 2.2.0-alpha-361_

**Comment by nirinchev** [comment] 2018-02-28 10:34
I've done some investigation and now have clarity on the root cause. The issue is that you're subscribing on the same collection. Only the first time the collection subscribes for changes, an actual subscription is created:

https://github.com/realm/realm-dotnet/blob/master/Realm/Realm/RealmCollectionBase.cs#L166

Subsequent managed subscriptions will reuse the existing native subscription. The reason s2 gets invoked is that it's created before the native callback is invoked for the first time. After the first `waitAsync`, the callback is invoked, notifying both s1 and s2. Then, s3 gets created, but at that point the `d.Friends` collection has already been notified with the initial state, so the callback will be invoked only after something in the collection changes.

There are two workarounds - if you obtain a new dummy object, e.g.:

```cs
var dRef = ThreadSafeReference.Create(d);
var d1 = realm.ResolveReference(dRef);

// d1 is new instance, so d.Friends will be a different instance from d1.Friends
var s3 = d1.Friends.SubscribeForNotifications(helper);
```

the callback will be invoked for `d1.Friends`. Alternatively, if you unsubscribe the existing callbacks by disposing s1 and s2, this will remove the native subscription, so when s3 is created, that will be recreated and the callback will be invoked with `changes == null`.

The real fix, however, is a bit challenging. We could easily modify `SubscribeForNotifications` and add an else case:

```cs
if (_callbacks.Count == 0)
{
    SubscribeForNotifications();
}
else
{
    callback(this, null, null)
}
```

but this may be surprising as the callback will be invoked during subscribing and not after that. I'll have to think about it for a while, but if that is something that would work for your case, I'd be happy to create a PR and build a nuget package from that.

**Comment by nielsenko** [comment] 2018-02-28 22:01
I don't find it particular surprising that the callback happens on the same call-stack as the subscription. Actually, I did find it surprising at first, when I realised that this is not the case in realm-dotnet today. 

So such a fix would be very welcome for my part. I would like to avoid, that `initCalls` is incremented twice for `s2`, once as today, and once since `_callback.Count > 0`, but alas it is a lesser evil than not being called at all.

**Comment by nirinchev** [comment] 2018-02-28 22:36
I'll see what can be done about it. Off the top of my head, we can store a `deliveredInitialNotification` field on the collection and only do the manual callback invocation if that is true, but it's possible there are better approaches. I'll create a quick PR tomorrow morning for that and share the package with you when we have.

**Comment by nirinchev** [comment] 2018-03-02 14:19
Here's links to the prerelease packages:

[Realm](https://drive.google.com/file/d/1aT4ZurHABDs878DK7WpHNQmGFPbh_9lV/view?usp=sharing)
[Realm.Database](https://drive.google.com/file/d/1sJmqrZM1KDaroxr77MMZn-jViHQliv5Z/view?usp=sharing)

**Closed** 2018-03-12 17:49 UTC
