### ISSUE TITLE
Application freezes

### ISSUE THREAD

**Issue by madcreep** [realm/realm-dotnet#1664] opened 2017-12-18 11:39 UTC
Hi!

We use Realm in a mobile application, and sometimes the app freezes during a list update from Realm DB.

Here's ho we get Realm instance:
`readonly static Nito.AsyncEx.AsyncLock _mutex = new Nito.AsyncEx.AsyncLock();
        public static Realm GetRealm()
        {
            using (_mutex.Lock())
            {
                return Realm.GetInstance(RealmConfiguration.DefaultConfiguration);
            }
        }`

Here's how we update data in a DB:

`readonly static Nito.AsyncEx.AsyncLock _updateMutex = new Nito.AsyncEx.AsyncLock();
        public static async Task UpdateAsync(Action<Realm> action)
        {
            using (await _updateMutex.LockAsync())
            {
                var realm = GetRealm();
                await realm.WriteAsync((realmWrite) => {
                    action(realmWrite);
                });
            }
        }`
Everything  with data is being done with these two methods.

Realm version 2.1.0
Microsoft.NETCore.UniversalWindowsPlatform 6.0.5
Xamarin.Forms 2.5.0.121934

![photo_2017-12-18_14-36-20](https://user-images.githubusercontent.com/2410787/34104288-dfa020c8-e400-11e7-921e-834be9cc8e0a.jpg)

It is hard to make a demo app, because we couldn't reproduce the issue in a small application (though the mobile developer claims he will try to do that nevertheless).

**Comment by nirinchev** [comment] 2017-12-18 12:08
We'll need more information to be able to analyze the problem. If you're unable to reproduce the issue in a small app, you can still share your actual application privately at help@realm.io.

**Comment by madcreep** [comment] 2017-12-18 12:13
Well, thanks for your answer!

Would you be needing source code with the application, or is it enough just to send the binaries?

**Comment by nirinchev** [comment] 2017-12-18 12:14
Source code would be ideal so we can see what is the application doing when it locks up.

**Comment by madcreep** [comment] 2017-12-19 12:11
Seems we've managed to reproduce the issue after all.

[MyCity.zip](https://github.com/realm/realm-dotnet/files/1571591/MyCity.zip)

**Comment by madcreep** [comment] 2017-12-25 07:43
@nirinchev, hi.
Did you manage to reproduce the issue? Thanks.

**Comment by nirinchev** [comment] 2017-12-27 00:34
I was able to reproduce it, but haven't been able to determine with 100% accuracy what the cause is. Still, I am very confident it's related to the way your project is setup. Currently, every object creates a write transaction whenever it wants to update itself, which means you can theoretically have tens or hundreds (or more) transactions for a single update from the server. This puts a lot of stress on the TPL as it creates a task for each update. When I reproduced the locks, `Concurrency::PPLTask::ScheduleTask` was the only active task. So to fix it, you must change your architecture to open a single transaction, perform all the updates in there, then commit it. This would be hugely beneficial in terms of speed as well, as right now there are some artificial locks that should not be necessary.

As an additional warning point, you tend to open Realms without disposing them which could lead to problems if done on a background thread. Right now it seems you only open them on the main thread, which is fine, but keep in mind that Realms open on a background thread must be disposed.

**Comment by madcreep** [comment] 2017-12-27 10:22
Hi, Nikola.
Thanks for your advice, we grouped more database actions into single transactions. The quantity of transactions got far less, the app became much more stable, but it still freezes sometimes.

**Comment by madcreep** [comment] 2017-12-28 07:11
Hi.
My buddy sais he figured out what happens: if during one transaction opens another (in different thread), application inevitably freezes. This happens on UWP only, on Android and iOS there's no such a thing.

**Comment by sidgo28** [comment] 2019-03-28 17:39
Hi @nirinchev , we're about to release our Xamarin Native app which is in production for more than a year.  The only thing that stopping us is this bug. We're using the latest version but this bug still affects our app. The most frustrating about this is it will happen fore sure after an arbitrary number of updates. Our app is a real-time note taking app so it's unavoidable to have a number of writes in a few seconds.

We've already identified where the freeze occurs, and it's in realm.BeginWrite() or realm.Write() methods. Our conclusion is that the freeze occurs in the constructor of the Transaction class, which calls Realm::begin_transaction method in the shared_realm.cpp file in the Realm Object Store repo.

This is a very serious bug for anyone using .NET Realm because, as I've said, you can expect a freeze almost in every significant session of using the app.

Here's what we've done already:
1. Grouping multiple writes into one transaction. 
2. We've even went as far as making sure only one transaction is committed within two seconds.

And now, we're really not sure what to do next to remedy the bug, so any suggestion will be appreciated. Thank you very much.

**Comment by nirinchev** [comment] 2019-03-28 18:16
What platform are you targeting? This issue occurred only on UWP and is likely resolved in newer versions. How are you ensuring that only one transaction is committed? It sounds likely that you're introducing some sort of a deadlock, possibly by writing to a realm on multiple threads - realm.Write obtains a write lock, which is likely what you're seeing. A simplified example of a pattern that would cause deadlock is:

```csharp
private async void OnButtonClick()
{
    var transaction = realm.BeginWrite();
    await DoSomething();
    transaction.Commit();
}

private Task DoSomething()
{
    return Task.Run(() =>
    {
        var bgRealm = Realm.GetInstance();
        bgRealm.Write(() => bgRealm.Add(new Foo()));
    });
}
```

As this is not a problem that's previously been reported (except for this one UWP issue), and we do have customers running Realm .NET-based apps in production, I am inclined to think you're either hitting a very peculiar corner case or you're accidentally causing a deadlock situation.

**Comment by sidgo28** [comment] 2019-03-28 19:54
Hi @nirinchev . Thank you for responding.

First of all, yes, the bug is exclusive to the UWP version of our app. 

Second, we don't do multi-threading anywhere in our app especially in our data layer as we know it as a limitation in Realm. So there's a very small chance for a deadlock to happen. Also, our data layer is the only one that has reference to the actual realm and hence it's highly encapsulated, so we're sure that there's no accidental multi-threading introduced in the code. Also, here are the two versions of the method we used and we're using now:

```
// This is the method we're using before 
public static void Execute(this Realm realm, Action action) {
    if (realm.IsInTransaction) {
        action();
    } else {
        using (var t = realm.BeginWrite()) {
            action();
            t.Commit();
        }
    }
}

// This is the method we're using now
public static void Execute(this Realm realm, Action action) {
    if (realm.IsInTransaction) {
        _lastAction = DateTimeOffset.Now;
        action();
    } else {
        var t = realm.BeginWrite();
        action();

        TryCommit();

        void TryCommit() {
            if (DateTimeOffset.Now.Subtract(_lastAction).TotalMilliseconds < 2000) {
                Schedule();
            } else {
                using (t) {
                    _lastAction = DateTimeOffset.Now;
                    t.Commit();
                }
            }
        }

        void Schedule() {
            Task.Delay(2000)
                .ContinueWith(task => { TryCommit(); }, TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}
```
The first one frequently results to a freeze, and it's very easy to reproduce. Just rapidly check, for example, a checkbox whose IsChecked is bound to a realm object, hence sending a write transaction to the realm database every time.

We significantly reduced these freezes using the second method. As you can see, what this method does is it makes sure that only 1 transaction is committed to the database within 2 to 4 seconds. However, this method still produces a freeze in the `var t = realm.BeginWrite()` statement, especially when this statement is called immediately after the last transaction is committed (i.e., after about two seconds have passed after the last action).

**Comment by nirinchev** [comment] 2019-03-28 20:30
Hm, then that looks similar to this issue (I got thrown off because you mentioned Xamarin native). The method you posted seems reasonable, especially if you have guarantees that you're only using Realm on the main thread and that you only have a single instance. Just to be clear, are you on the latest version of the SDK?

**Comment by sidgo28** [comment] 2019-03-28 20:36
@nirinchev. Yes, we're using v3.4.0. But we started experiencing these freezes during version 2.x when we began development (more than a year ago, around the time this issue was created) though we didn't know at that time what's the cause of the freezes.

**Closed** 2021-01-18 15:45 UTC
Labels: O-Community, T-Bug
