### ISSUE TITLE
IRealmCollection does not update UWP ListView

### ISSUE THREAD

**Issue by denizcan** [realm/realm-dotnet#1935] opened 2019-12-21 15:01 UTC
This is the same as closed issue #1461. This time it is on 4.2.0 version of Realm..

When I assign a IRealmCollection to ListView.ItemsSource, ListView populates initial items, however further updates, additions/deletions are not reflected to the list.. I observed CollectionChanged event, it is called with correct arguments.. I suspect that ListView does not listen CollectionChanged event if the ItemsSource is IReadOnlyCollection.. When I place an ObservableCollection in the middle and add remove items in the callback, list is updated correctly..

**Comment by denizcan** [comment] 2019-12-21 15:23
Regarding to #1759 it looks like UWP apps cannot benefit this.. It is weird though..

**Comment by nirinchev** [comment] 2020-08-26 20:14
Closing as a duplicate of #1759.

**Closed by nirinchev** 2020-08-26 20:14 UTC
Labels: O-Community
