### ISSUE TITLE
On Xamarin Android when trying to apply permissions using Realms.Sync.User.Current.ApplyPermissionsAsync() this call gets stuck and doesn't apply permissions

### ISSUE THREAD

**Issue by rdelrosario** [realm/realm-dotnet#1734] opened 2018-05-13 21:13 UTC
When using Realm Platform Cloud cannot get permissions applied using **Realms.Sync.User.Current.ApplyPermissionsAsync** call gets stuck.

```cs
await Realms.Sync.User.Current.ApplyPermissionsAsync(RLM.PermissionCondition.UserId("*"), "*", RLM.AccessLevel.Write);
```

## Goals

Be able to apply write/read permissions to Realm

## Expected Results

Should get permissions applied  and task returned after this call 

## Actual Results

When calling **Realms.Sync.User.Current.ApplyPermissionsAsync** never gets response this call gets stuck and doesn't apply the permissions.

## Steps to Reproduce

1. Create a realm platform cloud instance
2. Create a realm path with some classes inside.
3. Create a Realm User 
4. Change user type to Admin
4. Try to login with username/password
5. Try to apply permissions using using **Realms.Sync.User.Current.ApplyPermissionsAsync**
6. Verify on Realm Studio if permission got applied

## Code Sample

```cs
await Realms.Sync.User.Current.ApplyPermissionsAsync(RLM.PermissionCondition.UserId("*"), "*", RLM.AccessLevel.Write);
```

## Version of Realm and Tooling

- Realm Cloud

- Flavor:
  - [X] Developer
  - [ ] Professional
  - [ ] Enterprise

- Client SDK Version:  3.0.0
- Client OS & Version: Android 6.0

**Comment by nirinchev** [comment] 2018-05-14 07:33
Are you calling this on the main thread? Additionally, can you wrap the call in a try-catch block and verify if an exception is thrown?

**Comment by rdelrosario** [comment] 2018-05-14 12:43
Yes main thread and is wrapped on a try-catch block.

**Comment by rdelrosario** [comment] 2018-05-14 13:47
This fires no exception and gets stuck on that call:
```cs
try
{
   await Realms.Sync.User.Current.ApplyPermissionsAsync(Realms.Sync.PermissionCondition.UserId("*"), "*", Realms.Sync.AccessLevel.Write);

}catch(Exception ex){
						
}
```

**Comment by rdelrosario** [comment] 2018-05-15 21:33
Not happening on iOS after deleting my instance and creating a new one. But is happening on Xamarin Android @nirinchev any ideas?

**Comment by Char0394** [comment] 2018-05-18 16:58
Getting this issue as well on Android.

**Comment by nirinchev** [comment] 2018-06-22 11:53
This is caused by the fact we don't use the centralized certificate store on Android. Internally we force certificate validation when changing permissions but we don't load the CA certificates to actually validate the cloud certificates. This should be fixed when we update to the latest sync.

**Comment by nirinchev** [comment] 2018-06-22 11:54
Fixing it is tracked by https://github.com/realm/realm-dotnet/issues/1727, so I'll close this issue.

**Closed by nirinchev** 2018-06-22 11:54 UTC
Labels: O:User
