### ISSUE TITLE
[Bug]: NotifyCollectionChangedEventArgs OldItem is InvalidObject when updating the data

### ISSUE THREAD

**Issue by Lakshminatarajan** [realm/realm-dotnet#2752] opened 2021-12-15 16:35 UTC
### What happened?

We are using Realms object and in Syncfusion ListView. We have a realm query that is bound to the ItemsSource of the list like below,

```
            var realm = Realm.GetInstance();
            
            //just clean everything
            realm.Write(() => realm.RemoveAll());

            realm.Write(() =>
            {
                for (int i = 0; i < 10; i++)
                {
                    realm.Add(new ItemModel()
                    {
                        Title = i.ToString(),
                        Subtitle = Guid.NewGuid().ToString("N").Substring(0, 5),
                        IsDirectory = false
                    });
                }
            });

            var query = realm.All<ItemModel>().Where(im => im.IsDirectory == true);
            listview.ItemsSource = query;
```

The list will have the items with IsDirectory is true. When updating the IsDirectory to false, the item is removed from the query and the CollectionChanged event is fired with Remove action. 

The problem we are facing is, in the **NotifyCollectionChangedEventArgs**, the olditem is **InvalidObject**.
![image](https://user-images.githubusercontent.com/50870908/146215179-575e495b-b14c-4523-9e86-b9409953134f.png)

Due to this, we could not get the proper item in the syncfusion level to update the SfListView. Since the removed item is invalidobject, we could not get the proper index/item to remove it from our end.

**Note**: The issue occurs from version 10.4.0. Before this version, the OldItem is null.

We need the e.OldItems as actual data or null to process in the syncfusion source level.

### Repro steps

1. Run the attached sample ([ReplicationSample](https://www.syncfusion.com/downloads/support/common/1057/ze/ReplicationSample_eca11dfb.zip))
2. Click update
3. The IsDirectory property is updated, and the CollectionChanged event will be triggered. But, the OldItem is invalidobject.

### Version

10.7.0

### What SDK flavour are you using?

Local Database only

### What type of application is this?

Xamarin

### Client OS and version

10.7.0

### Code snippets

        private void OnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            Debug.WriteLine($"<||> OnCollectionChanged. {e.Action}, {e.NewItems?.Count}, {e.OldItems?.Count}");

            if (e.Action == NotifyCollectionChangedAction.Remove)
            {
                var oldItem = e.OldItems[0];
                if (oldItem == null)
                {
                    //The olditem is null till v10.3.0
                    Debug.WriteLine("OldItem is: " + oldItem);
                }
                else
                {
                    //Invalidate object passed as olditem from v10.4.0
                    Debug.WriteLine("OldItem is: " + oldItem);
                }
            }
        }

### Stacktrace of the exception/crash you're getting

```shell
NA
```

### Relevant log output

```shell
NA
```

**Comment by papafe** [comment] 2021-12-15 16:46
Hi @Lakshminatarajan, unfortunately you cannot obtain the old object, but only its index, as the object does not exist anymore in the database. 
And you're correct that before version 10.4 `OldItem` would have been null. In following versions we use `InvalidObject` to solve a bug with WPF (https://github.com/realm/realm-dotnet/issues/1903)

**Comment by IngweLand** [comment] 2021-12-15 16:57
@papafe 
In that particular case (not sure if it matters or not), the object still exists in the database. It's only removed from current query.
You can check my original report to the issue here https://www.syncfusion.com/feedback/30966/using-sflistview-with-realm-db-does-not-work-as-expected-when-updating-data-in

**Comment by papafe** [comment] 2021-12-15 17:50
@IngweLand yes, I expressed myself wrongly. What I meant is that the object is not anymore in the collection. 
The underlying API works the same though, as it's not possible to access the object that's been removed, but only its index.

**Comment by peppy** [comment] 2021-12-16 02:54
There's some similar discussion [here](https://github.com/realm/realm-dotnet/discussions/2634) on the same subject. We faced a similar case of wanting to receive the old object (when it is still in the database but not in the collected) but as mentioned above, this is not feasible.

**Comment by nirinchev** [comment] 2022-01-03 12:36
@fealebenpae I remember you had an idea to freeze the old object before the deletion occurs - do you have a rough estimate how much of an effort this is? Perhaps we can squeeze it into the next quarter plan for Core?

**Comment by fealebenpae** [comment] 2022-01-04 15:09
My idea was to deliver a frozen copy of the realm before we advance the read transaction to the latest version and deliver the notification payload together with the frozen realm and populate `OldItems` with objects from the frozen realm. That might take more time convincing than implementing, because AFAIK other SDKs don't need to worry about delivering object references for moves and deletes. Sounds like a good candidate for a scope doc to drive the conversation.

**Comment by ianpward** [comment] 2022-01-04 16:10
I would be in favor of adding explicit support to Core for both Moves and Deletes. I believe there are use cases for both

**Comment by papafe** [comment] 2022-03-29 09:12
Duplicate of https://github.com/realm/realm-dotnet/issues/1600

**Closed by papafe** 2022-03-29 09:12 UTC
Labels: O-Community
