### ISSUE TITLE
Update to Fody 6.0.0

### ISSUE THREAD

**Issue by hbhadauria** [realm/realm-dotnet#1899] opened 2019-08-26 05:51 UTC
## Goals
Update Fody package to latest version 6.0.0

## Expected Results
Realm Fody dependency is updated to latest version 6.0.0

## Actual Results
Current supported Fody version 4.0.2
Other libraries that have upgraded to latest Fody, resulting in issue with realm library.

## Steps to Reproduce
NA

## Code Sample
NA

## Version of Realm and Tooling
- Client SDK Version: realm-dotnet 4.1.0 for Xamarin.iOS and Xamarin.Android
- Client OS & Version: iOS - 12.4 and Android 9 Pie

**Comment by ryan-payet-wcc** [comment] 2019-09-05 00:26
I support this.  Realm is now no longer compatible with latest version of some packages such ReactiveUI, which now has a dependency on Fody >= 6.0

**Comment by aerazo** [comment] 2019-09-11 17:53
Every time that I update Fody in VS for Mac, I should to reinstall Realm again, always happen

**Comment by thinkaboutcsharp** [comment] 2019-09-24 01:01
I caught error "Fody: Failed to execute weaver". Is this caused by this issue?

Fody: Failed to execute weaver C:\Users\SETUP\.nuget\packages\realm.fody\4.1.0\build\..\weaver\net46\Realm.Fody.dll due to a MissingMemberException. Message: メソッドが見つかりません: 'Mono.Collections.Generic.Collection`1<Mono.Cecil.TypeReference> Mono.Cecil.GenericParameter.get_Constraints()'. This is likely due to the weaver referencing an old version (4) of Fody.

**Comment by nirinchev** [comment] 2019-09-24 05:00
It is, you need to downgrade your Fody version to 5.x.

**Comment by salgiza** [comment] 2019-10-02 07:52
We can add PropertyChanged.Fody (3.1.x) to the list of nuget packages that are now incompatible with Realm due to this.

**Comment by HobDev** [comment] 2019-10-06 11:35
This is a frequent issue. Why can't realm push a patch with every update in it's dependencies? Is this a big deal

**Comment by nirinchev** [comment] 2019-10-06 15:42
We have more important issues in the backlog that we'd like to address first. We'll get to upgrading it eventually.

**Comment by jitendrajadav** [comment] 2019-10-07 06:37
I am getting same error please check 
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: Failed to execute weaver C:\Users\...\.nuget\packages\realm.fody\4.1.0\build\..\weaver\net46\Realm.Fody.dll due to a MissingMemberException. Message: Method not found: 'Mono.Collections.Generic.Collection`1<Mono.Cecil.TypeReference> Mono.Cecil.GenericParameter.get_Constraints()'.. This is likely due to the weaver referencing an old version (4) of Fody.			1	
`

Now the problem fody is comes with Realm itself so I can't downgrade only fody it's dependency of Realm.

Please help me to fix this.
Note : I  can downgrade Realm itself but this is not right solution for me I have to do many thing in my code there are certain things I have updated with this

**Comment by nirinchev** [comment] 2019-10-07 07:33
Why can't you downgrade Fody?

**Comment by thinkaboutcsharp** [comment] 2019-10-07 07:44
In my case, I got PropertyChanged.Fody from nuget, its Fody was ver.6, so they were conflicted.
I want to use Realm database for xamarin, I gave up PropertyChanged.Fody.

**Comment by salgiza** [comment] 2019-10-07 07:51
@thinkaboutcsharp Until this ticket is fixed, instead of installing the last version of PropertyChanged.Fody (3.1.1) install de nugget package for version 3.0.1 ( https://www.nuget.org/packages/PropertyChanged.Fody/3.0.1 ), which is compatible with the current version of Realm.

**Comment by jitendrajadav** [comment] 2019-10-07 09:13
> Why can't you downgrade Fody?

Fody is inside the Realm please check screen short
![image](https://user-images.githubusercontent.com/1029026/66299270-ce377400-e910-11e9-93e0-04bfe017cdd2.png)

**Comment by nirinchev** [comment] 2019-10-07 09:44
@jitendrajadav you're referencing `PropertyChanged.Fody@3.1.3` which is why the Fody dependency is resolved as 6.0.0. As @salgiza mentioned, you can downgrade to `PropertyChanged.Fody@3.0.1` to be compatible with Fody 4/5.x.

**Comment by jitendrajadav** [comment] 2019-10-07 09:57
> @jitendrajadav you're referencing `PropertyChanged.Fody@3.1.3` which is why the Fody dependency is resolved as 6.0.0. As @salgiza mentioned, you can downgrade to `PropertyChanged.Fody@3.0.1` to be compatible with Fody 4/5.x.

@nirinchev Thank you for updating me I forgot to address this issue now problem is resolved by downgrading `PropertyChanged.Fody@3.0.1`

really appreciate

**Closed** 2019-10-07 21:02 UTC
Labels: O-Community
