### ISSUE TITLE
RealmInteger Equals implementation is not symmetric

### ISSUE THREAD

**Issue by papafe** [realm/realm-dotnet#2204] opened 2021-01-26 08:47 UTC
The implementation of `Equals` of `RealmInteger` is not symmetric when compared with native primitives. For instance:

```C#
RealmInteger<int> ri = 10;
long value = 10;

value.Equals(ri) // true
ri.Equals(value) // false
```

**Comment by LaPeste** [comment] 2021-02-08 11:22
I'm a bit confused by this issue, maybe I'm not understanding what we're after. I'm saying this because, this lack of symmetry is by design. The following has the same behaviour.
```
int valInt = 5;
long valLong = 5;
		
valInt.Equals((valLong); // false
valLong.Equals(valInt); // true
```
And this is just the way implicit conversion works. A long can't be implicitly converted to int, while an int can be implicitly converted to long, and this is what we're seeing in the issue under examination. On the other hand, if you explicitly cast the long to int, then it's all fine.

```
int valInt = 5;
long valLong = 5;
		
valInt.Equals((int)valLong); // true
valLong.Equals(valInt); // true
```

Perhaps, with this issue we want to cast behind the scene any numeric value to long, since this is the way we always store `RealmValues`? Although, this is `RealmInteger` and I'm not sure we want to use the same concept here. Also this would create problems anyway like the following
```
RealmInteger<long> ri = 10;
int value = 10;

value.Equals(ri) // false
ri.Equals(value) // true
```
And such problem can be solved again with an explicit cast for long to int.

**Comment by papafe** [comment] 2021-02-08 12:02
Yes, you're right that underneath everything saved in a `RealmInteger` should be backed up by a long, so it should be theoretically be possible. I have created this ticket while I was working on Mixed, because I thought it was a strange behaviour, as `Equals` should be [symmetric](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type). 
After talking with @nirinchev some time afterwards regarding a similar issue we also reached the conclusion that in the end it's behaving in a similar way as the primitive types. If the implicit operators weren't there it would actually be symmetric, so in my opinion we could just close this.

**Comment by LaPeste** [comment] 2021-02-08 12:48
No, in a `RealmInteger` the value is stored with the correct type `T`, not with a `long`. That behaviour is used only for `RealmValue`s. So the only way I can think of to achieve this symmetry, while retaining acceptable performance, is by having a lot of if-else branches to explicitly cast the **"other"** value to match the type of T.
Anyway, I will close this issue, then.

**Closed** 2021-02-09 13:17 UTC
