### ISSUE TITLE
Deleting data-bound objects lead to InvalidOperationExceptoin

### ISSUE THREAD

**Issue by wyvern610** [realm/realm-dotnet#1270] opened 2017-03-10 08:07 UTC
using (var transaction = realm.BeginWrite())
            {
                for (int i = 0; i < 1000; i++)
                {
                    var person = new RealmPerson();
                    person.Name = "name" + i;
                    person.Age = i;
                    realm.Add(person);
                }
                transaction.Commit();
            }
            listView.ItemsSource = realm.All<RealmPerson>().AsRealmCollection();
            using (var transaction = realm.BeginWrite())
            {
                realm.RemoveAll<RealmPerson>();
                transaction.Commit();
            }

RealmCollection implements INotifyCollectionChanged interface.
so expected results are No Exception?

**Comment by nirinchev** [comment] 2017-03-13 10:01
Can you paste the whole exception object?

**Comment by wyvern610** [comment] 2017-03-13 23:35
System.InvalidOperationException はハンドルされませんでした。
  HResult=-2146233079
  Message=指定されたインデックス '999' で、追加された項目が表示されません。
  Source=PresentationFramework
  StackTrace:
       場所 MS.Internal.Data.EnumerableCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
       場所 System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
       場所 Realms.RealmCollectionBase`1.RaiseCollectionChanged(NotifyCollectionChangedEventArgs args) 場所 C:\jenkins\workspace\realm_realm-dotnet_PR-1259-S2QELV65P7BDGRCDIBL2GFPGLFT2KXZLPVJ5URX7TYYZ6DVN3OAQ\Shared\Realm.Shared\RealmCollectionBase.cs:行 259
       場所 Realms.RealmCollectionBase`1.OnChange(IRealmCollection`1 sender, ChangeSet change, Exception error) 場所 C:\jenkins\workspace\realm_realm-dotnet_PR-1259-S2QELV65P7BDGRCDIBL2GFPGLFT2KXZLPVJ5URX7TYYZ6DVN3OAQ\Shared\Realm.Shared\RealmCollectionBase.cs:行 243
       場所 Realms.RealmCollectionBase`1.Realms.RealmCollectionNativeHelper.Interface.NotifyCallbacks(Nullable`1 changes, Nullable`1 exception) 場所 C:\jenkins\workspace\realm_realm-dotnet_PR-1259-S2QELV65P7BDGRCDIBL2GFPGLFT2KXZLPVJ5URX7TYYZ6DVN3OAQ\Shared\Realm.Shared\RealmCollectionBase.cs:行 319
       場所 Realms.RealmCollectionNativeHelper.NotificationCallbackImpl(IntPtr managedResultsHandle, IntPtr changes, IntPtr exception) 場所 C:\jenkins\workspace\realm_realm-dotnet_PR-1259-S2QELV65P7BDGRCDIBL2GFPGLFT2KXZLPVJ5URX7TYYZ6DVN3OAQ\Shared\Realm.Shared\Linq\RealmCollectionNativeHelper.cs:行 38
       場所 Realms.SynchronizationContextEventLoopSignal.EventLoop.<>c__DisplayClass3_0.<Post>b__0(Object _) 場所 C:\jenkins\workspace\realm_realm-dotnet_PR-1259-S2QELV65P7BDGRCDIBL2GFPGLFT2KXZLPVJ5URX7TYYZ6DVN3OAQ\Shared\Realm.Shared\Native\SynchronizationContextEventLoopSignal.cs:行 65
       場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       場所 System.Windows.Threading.DispatcherOperation.InvokeImpl()
       場所 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       場所 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       場所 System.Windows.Threading.DispatcherOperation.Invoke()
       場所 System.Windows.Threading.Dispatcher.ProcessQueue()
       場所 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       場所 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       場所 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       場所 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       場所 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       場所 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       場所 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       場所 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       場所 System.Windows.Application.RunDispatcher(Object ignore)
       場所 System.Windows.Application.RunInternal(Window window)
       場所 System.Windows.Application.Run(Window window)
       場所 System.Windows.Application.Run()
       場所 WpfRealmTestApp2.App.Main()
       場所 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       場所 System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       場所 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       場所 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       場所 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       場所 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       場所 System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by nirinchev** [comment] 2017-03-15 16:47
That doesn't look like an exception in Realm itself, more like the control you've bound the collection to. Can you share a minimal repro project so we can further investigate?

**Comment by wyvern610** [comment] 2017-03-16 21:10
It's simple to reproduce this.

This is MainWindow and RealmPerson class.

`    public partial class MainWindow : Window
    {
        private Realm realm;

        public MainWindow()
        {
            InitializeComponent();
            var path = System.IO.Path.ChangeExtension(Environment.GetCommandLineArgs()[0], ".realm");
            var realmConfig = new RealmConfiguration(path);
            realm = Realm.GetInstance(realmConfig);
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            using (var transaction = realm.BeginWrite())
            {
                for (int i = 0; i < 1000; i++)
                {
                    var person = new RealmPerson();
                    person.Name = "name" + i;
                    person.Age = i;
                    realm.Add(person);
                }
                transaction.Commit();
            }
            listView.ItemsSource = realm.All<RealmPerson>().AsRealmCollection();
            using (var transaction = realm.BeginWrite())
            {
                realm.RemoveAll<RealmPerson>();
                transaction.Commit();
            }
        }
    }

    public class RealmPerson : RealmObject
    {        
        public string Name { get; set; }
        public int Age { get; set; }
    }`

and Xaml for MainWindows is like the following

<Window x:Class="WpfRealmTestApp3.MainWindow" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:d="http://schemas.microsoft.com/expression/blend/2008" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:local="clr-namespace:WpfRealmTestApp3" mc:Ignorable="d" Title="MainWindow" Height="350" Width="525"> <StackPanel Orientation="Vertical"> <Button Click="Button_Click" Content="Click!"/> <ListView x:Name="listView"/> </StackPanel> </Window>

**Comment by nirinchev** [comment] 2017-03-21 14:27
This looks like an issue with WPF's `ListView`. I imagine it attempts to read the deleted objects which is not supported. With Forms we solved it with the `IReflectableType` implementation where the getters return the default values if the object is not managed by a Realm.

**Comment by trevorm7** [comment] 2019-09-26 04:58
Unfortunately this is still an issue. I have a workaround where you assign the realm as a list like this:
`Projects_ListView.ItemsSource = realm.All<Project>().ToList();`
Then you put this after any code that adds, removes or changes an item:
`Projects_ListView.ItemsSource = realm.All<Project>().ToList();`

Unfortunately this is annoying to code and has a negative effect on UX because it has to completely reload the list every time you change something.

**Comment by nirinchev** [comment] 2020-09-02 00:45
This is a duplicate of https://github.com/realm/realm-dotnet/issues/1903.

**Closed by nirinchev** 2020-09-02 00:45 UTC
Labels: O-Community, T-Bug
