### ISSUE TITLE
Fody exception after updgrading to 0.77

### ISSUE THREAD

**Issue by alexrainman** [realm/realm-dotnet#727] opened 2016-07-21 23:39 UTC
> **Bugs**: 

```
Errors:

/Users/username/Projects/LoadChart/packages/Fody.1.29.4/build/portable-net+sl+win+wpa+wp/Fody.targets (FodyTarget target) ->

	: error : Fody: An unhandled exception occurred:
Exception:
Value cannot be null.
Parameter name: type
StackTrace:
  at Mono.Cecil.ModuleDefinition.ImportReference (Mono.Cecil.TypeReference type, IGenericParameterProvider context) <0x39a3720 + 0x0009b> in <filename unknown>:0 
  at Mono.Cecil.ModuleDefinition.ImportReference (Mono.Cecil.TypeReference type) <0x39a36f0 + 0x0001f> in <filename unknown>:0 
  at ModuleWeaver.Execute () <0x36cbd58 + 0x009ff> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object)
  at InnerWeaver.ExecuteWeavers () <0x36cb7b8 + 0x001b0> in <filename unknown>:0 
  at InnerWeaver.Execute () <0x3652a30 + 0x000df> in <filename unknown>:0 
Source:
Mono.Cecil
TargetSite:
Mono.Cecil.TypeReference ImportReference(Mono.Cecil.TypeReference, Mono.Cecil.IGenericParameterProvider)
```

**Comment by AndyDentFree** [comment] 2016-07-24 14:20
Closing as duplicate of #715

**Closed by AndyDentFree** 2016-07-24 14:20 UTC
