### ISSUE TITLE
Realm Xamarin.Android Unit Test System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by DrifterApps** [realm/realm-dotnet#1273] opened 2017-03-13 03:47 UTC
I'm trying to unit tests my Realm (1.1.0) implementation using a Xamarin.Android Unit Test project since I cannot unit test a PCL library.

I created a project, and added the following line which crashes:

`_realm = Realm.GetInstance();
`
I get the following error:

> Fail [FAIL] : System.PlatformNotSupportedException : The PCL build of Realm is being linked which probably means you need to use NuGet or otherwise link a platform-specific Realm.dll to your main application.
>           at Realms.RealmPCLHelpers.ThrowProxyShouldNeverBeUsed () [0x00000] in <a0bdda658c634b1e932b3ea414073102>:0 
>           at Realms.Realm.GetInstance (Realms.RealmConfigurationBase config) [0x00000] in <a0bdda658c634b1e932b3ea414073102>:0 
>           at DrifterApps.FeedTheHole.Core.Realms.TestRealmQueries.Setup () [0x00003] in /Users/patrick/Projects/FeedTheHole/Core.Realms.Tests/Realms/TestRealmQueries.cs:17 
>           at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
>           at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 
>     Ignore [INFO] : another time
> 

My project includes the Realm library as such:

```
<Reference Include="Remotion.Linq">
  <HintPath>..\packages\Remotion.Linq.2.1.1\lib\portable-net45+win+wpa81+wp80\Remotion.Linq.dll</HintPath>
</Reference>
<Reference Include="Realm">
  <HintPath>..\packages\Realm.Database.1.1.0\lib\MonoAndroid44\Realm.dll</HintPath>
</Reference>
<Reference Include="Realm.Sync">
  <HintPath>..\packages\Realm.1.1.0\lib\MonoAndroid44\Realm.Sync.dll</HintPath>
</Reference>
<Reference Include="DotNetCross.Memory.Unsafe">
  <HintPath>..\packages\DotNetCross.Memory.Unsafe.0.2.3.4\lib\netstandard1.0\DotNetCross.Memory.Unsafe.dll</HintPath>
</Reference>

```
Any ideas??

**Comment by AndyDentFree** [comment] 2017-03-13 04:57
I'd normally say you need to add the Realm Nuget to your Android Unit Test project but it looks like you already did that.

Try removing Realm NuGets and adding them again but select the 1.0.4 version. A new compilation process was added in 1.1.0 .

**Comment by nirinchev** [comment] 2017-03-13 10:07
Possibly duplicate of https://github.com/realm/realm-dotnet/issues/1271

**Comment by DrifterApps** [comment] 2017-03-13 22:15
I downgraded to version 1.0.4 and was able to run my tests.

**Comment by nirinchev** [comment] 2017-03-15 16:42
Can you verify if 1.1.1 fixes your problem?

**Comment by nirinchev** [comment] 2017-03-15 21:43
Glad to hear that! If anything else comes up, be sure to let us know.

**Closed by nirinchev** 2017-03-15 21:43 UTC
Labels: T:Bug, T:Duplicate
