### ISSUE TITLE
Realm Notification/Weak Realm Notifier crash

### ISSUE THREAD

**Issue by m-mccool** [realm/realm-dotnet#653] opened 2016-06-22 15:22 UTC
#### Goal

Stop the application crashing with sigsegv
It seems to be related to realm notifications, even though I am not using this feature.
I suspect this is a threading issue as it occurs on getting a notification from our server.
Is it anything to do with #557 ?
Is there a workaround?

```
2016-06-22 16:02:16.322 MyExampleApp[439:69565] critical: Stacktrace:
2016-06-22 16:02:16.322 MyExampleApp[439:69565] critical:   at <unknown> <0xffffffff>
2016-06-22 16:02:16.324 MyExampleApp[439:69565] critical:   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain (int,string[],intptr,intptr) <0xffffffff>
2016-06-22 16:02:16.325 MyExampleApp[439:69565] critical:   at UIKit.UIApplication.Main (string[],intptr,intptr) [0x00005] in /Users/builder/data/lanes/3234/d8bedd03/source/maccore/src/UIKit/UIApplication.cs:77
2016-06-22 16:02:16.325 MyExampleApp[439:69565] critical:   at UIKit.UIApplication.Main (string[],string,string) [0x0001c] in /Users/builder/data/lanes/3234/d8bedd03/source/maccore/src/UIKit/UIApplication.cs:60
2016-06-22 16:02:16.326 MyExampleApp[439:69565] critical:   at MyExampleApp.Main (string[]) [0x00001] in C:\MyExampleApp.iOS\Main.cs:12
2016-06-22 16:02:16.327 MyExampleApp[439:69565] critical:   at (wrapper runtime-invoke) object.runtime_invoke_dynamic (intptr,intptr,intptr,intptr) <0xffffffff>
2016-06-22 16:02:16.327 MyExampleApp[439:69565] critical: 
Native stacktrace:
2016-06-22 16:02:16.565 MyExampleApp[439:69565] critical: 	0   MyExampleApp                      0x00000001015a5af8 mono_handle_native_sigsegv + 260
2016-06-22 16:02:16.565 MyExampleApp[439:69565] critical: 	1   MyExampleApp                      0x00000001015ada10 mono_sigsegv_signal_handler + 328
2016-06-22 16:02:16.566 MyExampleApp[439:69565] critical: 	2   libsystem_platform.dylib            0x0000000181a0594c _sigtramp + 68
2016-06-22 16:02:16.566 MyExampleApp[439:69565] critical: 	3   MyExampleApp                      0x0000000101455fcc _ZN5realm5Realm6notifyEv + 32
2016-06-22 16:02:16.567 MyExampleApp[439:69565] critical: 	7   CoreFoundation                      0x0000000181d58910 <redacted> + 412
2016-06-22 16:02:16.567 MyExampleApp[439:69565] critical: 	8   CoreFoundation                      0x0000000181d56690 <redacted> + 724
2016-06-22 16:02:16.567 MyExampleApp[439:69565] critical: 	9   CoreFoundation                      0x0000000181c85680 CFRunLoopRunSpecific + 384
2016-06-22 16:02:16.567 MyExampleApp[439:69565] critical: 	10  GraphicsServices                    0x0000000183194088 GSEventRunModal + 180
2016-06-22 16:02:16.567 MyExampleApp[439:69565] critical: 	11  UIKit                               0x0000000186afcd90 UIApplicationMain + 204
2016-06-22 16:02:16.567 MyExampleApp[439:69565] critical: 	12  MyExampleApp                      0x0000000100c67934 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 324
2016-06-22 16:02:16.566 MyExampleApp[439:69565] critical: 	4   MyExampleApp                      0x0000000101455fcc _ZN5realm5Realm6notifyEv + 32
2016-06-22 16:02:16.566 MyExampleApp[439:69565] critical: 	5   MyExampleApp                      0x000000010145dafc _ZZN5realm5_impl17WeakRealmNotifierC1ERKNSt3__110shared_ptrINS_5RealmEEEbEN3$_08__invokeEPv + 36
2016-06-22 16:02:16.566 MyExampleApp[439:69565] critical: 	6   CoreFoundation                      0x0000000181d58efc <redacted> + 24
2016-06-22 16:02:16.568 MyExampleApp[439:69565] critical: 	13  MyExampleApp                      0x0000000100bf453c UIKit_UIApplication_Main_string___intptr_intptr + 44
2016-06-22 16:02:16.568 MyExampleApp[439:69565] critical: 	14  MyExampleApp                      0x0000000100bf44fc UIKit_UIApplication_Main_string___string_string + 172
2016-06-22 16:02:16.568 MyExampleApp[439:69565] critical: 	15  MyExampleApp                      0x0000000100010800 MYEXAMPLEAPP_IOS_Application_Main_string__ + 128
2016-06-22 16:02:16.568 MyExampleApp[439:69565] critical: 	16  MyExampleApp                      0x00000001003daf44 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
2016-06-22 16:02:16.568 MyExampleApp[439:69565] critical: 	17  MyExampleApp                      0x00000001015afe54 mono_jit_runtime_invoke + 1232
2016-06-22 16:02:16.568 MyExampleApp[439:69565] critical: 	18  MyExampleApp                      0x0000000101605ab4 mono_runtime_invoke + 124
2016
-06-22 16:02:16.568 MyExampleApp[439:69565] critical: 	19  MyExampleApp                      0x0000000101609ca8 mono_runtime_exec_main + 400
2016-06-22 16:02:16.568 MyExampleApp[439:69565] critical: 	20  MyExampleApp                      0x0000000101689108 xamarin_main + 1840
2016-06-22 16:02:16.569 MyExampleApp[439:69565] critical: 	21  MyExampleApp                      0x0000000101431d94 main + 96
2016-06-22 16:02:16.569 MyExampleApp[439:69565] critical: 	22  libdyld.dylib                       0x00000001818268b8 <redacted> + 4
2016-06-22 16:02:16.569 MyExampleApp[439:69565] critical: 
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
The app has been terminated.
The app has been terminated.
```

#### Expected Results

The error does not appear

#### Actual Results

See stack trace above

#### Steps & Code to Reproduce

I can only reproduce in our app, so far I have seen it when we receive a notification from our server then try an update an object in our realm

#### Code Sample

Cannot supply currently since it is private code. If you really need it to diagnose then I will attempt to provide an example

Further investigation - We call the code to update the realm in a task e.g

```
Task.Run(() => RequestFromServerThenUpdateLocalRealm()).ContinueWith((task, o) =>
{
    // Handle response
}, TaskScheduler.FromCurrentSynchronisationContext());
```

The app seems to crash when the ContinueWith processing finishes.

The strange thing is this is only happening on one of our requests. 

Each time we use the realm we use

```
using (var realm = ourService.GetRealm()
{
    // We are using transaction like this
    realm.Write(() =>
    {
        // read from and write to the realm
    }); 
}
```
So I am assuming that the realm should be closed and the transaction either commited or rolled back when the scope ends. Note we are using encryption.

#### Version of Realm and tooling
Tried both 0.76.0 and 0.76.1 both showing the issue

Visual Studio 2015 update 2

iOS 9.2

**Comment by fealebenpae** [comment] 2016-06-22 19:13
Hi @m-mccool,

Thank you for the detailed error report. Unfortunately, the stacktrace doesn't yield any specific information that I recognize.

#557 is Android-related, although something similar might be occurring here.

I'm afraid there isn't a workaround that turns off the calls to `Realm::notify()`. The `WeakRealmNotifier` family of classes, together with their `ExternalCommitHelper` counterparts, monitor a Realm file for changes - their main function is to notify a Realm instance whenever another instance (maybe on another thread or even process) has committed changes to the Realm file so that it can move to the latest version of the data in the database. This behavior is intrinsic to how a Realm operates - without it you'd always have to reacquire a fresh Realm instance, and is used beyond the change notification APIs.

From what I can tell, it seems that the crash occurs precisely when a Realm instance is being notified of changes. It would really help if you could provide a sample that reproduces this, either posting it publicly or sending it to help@realm.io if the code is sensetive and should not be shared.

Incidentally, what Xamarin version are you using?

**Comment by m-mccool** [comment] 2016-06-22 20:21
Hi,

Thanks for the quick response.

Currently when the data is retrieved from the realm, I create a new non-realm object by mapping the data to the new non-realm object from the realm object retrieved. Realm objects are not used outside the data access layer. I'm assuming this is usage pattern is OK.

It will be tomorrow before I can get the Xamarin version info to you.  





I

**Comment by m-mccool** [comment] 2016-06-23 09:31
Visual Studio INstalled Products
Xamarin 4.0.4.4 (a9c7826)
Xamarin.Android 6.0.4.0 (ee215fc)
Xamarin.iOS 9.6.2.2 (be25da5)

Xamarin Studio Installed Products (Used only for the agent for Visual Studio)

**Comment by fealebenpae** [comment] 2016-06-23 10:41
Thank you for the info. I don't think there's anything out of the ordinary here that might indicate a cause for the crash you're getting. I'm afraid a repro project, even a private one you can confidentially share to help@realm.io, is what we'll need to diagnose the root cause of the problem.

**Comment by m-mccool** [comment] 2016-06-23 11:38
Hi Yavor,

I am currently trying to tie down the piece of code which may be causing this. Once I get a repeatable scenario I will let you know

**Comment by m-mccool** [comment] 2016-06-23 16:42
I am having a little success with this, but do not yet have a repeatable solution in a demo app.

As I said earlier we initiate a request as follows

```
Task.Run(() => RequestFromServerThenUpdateLocalRealm()).ContinueWith((task, o) =>
{
    // Handle response
}, TaskScheduler.FromCurrentSynchronisationContext());
```
Note - I have also tried using the TaskScheduler.Default, but got the same result.

We also receive an update form the server, which is run on a threadpool thread. This also calls into the realm multiple times to update and retrieve realm objects. If I comment out the update processing in the client I do not get the issue, which makes sense. If I then enable the processing again, but limit the access to the realm, by caching some of the data, it takes a few attempts to make the crash happen. So it seems like a race condition or a the result of a cumulative requests. Could this be anything to do with the db access strategy I described 

```
public myObject MyDatabaseApi()
{
    MyObject myObject = null;
    using (var realm = ourService.GetRealm()
    {
        // We are using transaction like this
        realm.Write(() =>
        {
           // read from and write to the realm
           var myDaoObject = realm.All<MyDaoObject>().Where( x => x.Key = key).ToList().FirstOrDefault();
           myDaoObject.Value1 = someValue;
           
           // Create new non-realm object from the data in the real object
           myObject = new MyObject(myDaoObject.Value1, myDaoObject.Value2); 

       }); 
       return myObject;
    } 
}
```

Note, I use ToList() on most of my queries so that I can then use the full set of linq queries.

Is there anything you have to be aware of when accessing realm in a background thread? Looking at the documentation there doesn't seem to be (except passing realm objects between threads)

**Comment by m-mccool** [comment] 2016-06-23 17:45
I looked at the crash files and it is says it is crashing in the main UI thread. So my assumption that it is crashing in the continuation seems to be correct. 

Tomorrow I am going to be attempting to symbolicate the iOS crash file to see if it gives me any more information that might help

**Comment by m-mccool** [comment] 2016-06-24 14:18
Hi @fealebenpae I have just sent you (help@realm.io) a small app which replicates this issue. If you have any other queries let me know.

**Comment by fealebenpae** [comment] 2016-06-24 14:20
Thank you, I'll look into it right away.

**Closed** 2016-06-28 12:11 UTC
Labels: S:Review, T:Bug-Crash
