### ISSUE TITLE
Bug unhandled exception after updating from 0.76.1 to 0.77.0

### ISSUE THREAD

**Issue by UKDeveloper99** [realm/realm-dotnet#725] opened 2016-07-21 11:08 UTC
#### Goal

> Update from Realm v0.76.1 to Realm 0.77.0

#### Expected Results

> Update without build errors.

#### Actual Results

>
Fody/RealmWeaver:   Executing Weaver 
: error : Fody: An unhandled exception occurred:
Exception:
Value cannot be null.
Parameter name: type
StackTrace:
  at Mono.Cecil.ModuleDefinition.ImportReference (Mono.Cecil.TypeReference type, IGenericParameterProvider context) <0x36458d0 + 0x0009b> in <filename unknown>:0 
  at Mono.Cecil.ModuleDefinition.ImportReference (Mono.Cecil.TypeReference type) <0x36458a0 + 0x0001f> in <filename unknown>:0 
  at ModuleWeaver.Execute () <0x3604a28 + 0x009ff> in <filename unknown>:0 
  at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object)
  at InnerWeaver.ExecuteWeavers () <0x3604488 + 0x001b0> in <filename unknown>:0 
  at InnerWeaver.Execute () <0x30a84d0 + 0x000df> in <filename unknown>:0 
Source:
Mono.Cecil
TargetSite:
Mono.Cecil.TypeReference ImportReference(Mono.Cecil.TypeReference, Mono.Cecil.IGenericParameterProvider)
>
Fody:   Finished Fody 1019ms.
Task "Fody.WeavingTask" execution -- FAILED
Done building target "FodyTarget" in project "/Users/admin/Documents/Workspace/faradayappv2.ios_2/Core/FaradayAppV2.Core/FaradayAppV2.Core.csproj".-- FAILED
>	
Done building project "/Users/admin/Documents/Workspace/faradayappv2.ios_2/Core/FaradayAppV2.Core/FaradayAppV2.Core.csproj".-- FAILED
>
Build FAILED.
>
Warnings:
>
/Users/admin/Documents/Workspace/faradayappv2.ios_2/Core/FaradayAppV2.Core/FaradayAppV2.Core.csproj (Build) ->
/Library/Frameworks/Mono.framework/Versions/4.4.1/lib/mono/4.5/Microsoft.Common.targets (ResolveAssemblyReferences target) ->
>
/Library/Frameworks/Mono.framework/Versions/4.4.1/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'System.Collections.Immutable' not resolved
/Library/Frameworks/Mono.framework/Versions/4.4.1/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'MvvmCross.Plugins.DownloadCache' not resolved

#### Steps & Code to Reproduce

> Removed packages folder and rebuilt solution, various combinations of clean/rebuild, removing realm package,

#### Code Sample
>
A blank Xamarin.iOS app with a PCL core project.

#### Version of Realm and tooling
>
Realm version(s): 
0.76.1 
to 
0.77.0
>
Xamarin Studio 6.0.1 (Build 9)
Latest and greatest.

**Comment by AndyDentFree** [comment] 2016-07-24 14:19
Closing as duplicate of #715

**Closed by AndyDentFree** 2016-07-24 14:19 UTC
