### ISSUE TITLE
latest NuGet package for Xamarin.iOS gives app crash during early startup

### ISSUE THREAD

**Issue by ideveloperaz** [realm/realm-dotnet#1874] opened 2019-06-24 08:17 UTC
## Goals

install Realm on Xamarin.iOS with latest stuff

## Expected Results

App should be able to start on real device with added via NuGet Realm package

## Actual Results

App crashes after reaching app's launching screen on real device (early startup)!
On Simulator I could run app without problems. Issue only with real device

## Steps to Reproduce

1) install Realm from NuGet
2) add FodyWeavers.xml with Realm tag to project
3) compile and run on real device

## Code Sample

no codes added only NuGet packages and FodyWeavers.xml with the following content:
<?xml version="1.0" encoding="utf-8"?>
<Weavers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FodyWeavers.xsd"> 
    <Realm />
</Weavers>

## Version of Realm and Tooling

latest realm 4.0.0 (for 24 June 2019)

**Comment by ideveloperaz** [comment] 2019-06-24 08:22
PS: FodyWeavers.xml with only one tag "Realm"

**Comment by nirinchev** [comment] 2019-06-24 09:02
This is a duplicate of https://github.com/realm/realm-dotnet/issues/1871.

**Closed by nirinchev** 2019-06-24 09:02 UTC
Labels: O:User

**Comment by ideveloperaz** [comment] 2019-06-24 09:15
Also I could see in Build Output the following :


Target FodyTarget:
      Fody: Fody (version 5.1.0.0 @ file:///Users/userr/Documents/xProjects/git.company.com/Company.App/packages/Fody.5.1.0/netclassictask/Fody.dll) Executing
        Fody/Realm:   Executing Weaver 
        Fody/Realm:   Not weaving assembly 'Company.App.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it doesn't reference Realm.
      Fody:   Finished Fody 1328ms.
