### ISSUE TITLE
Build Warning MSB3277 with Realm 2.1.0 and Realm.DataBinding 1.2.0

### ISSUE THREAD

**Issue by EBusch** [realm/realm-dotnet#1665] opened 2017-12-20 21:43 UTC
When adding Realm to a new Forms project in Visual Studio I am receiving an MSB3277 build warning. It appears that Realm.DataBinding is still relying on Realm 1.6.0, instead of Realm 2.1.0. 

## Steps to Reproduce

Creating a new Forms project and adding Realm as a Nuget will get you there. If you set the debug level to Diagnostics it will give the full detail. Search the build log for "was chosen"

## Version of Realm and Tooling

- Realm Object Server Version: 2.1.0
- Flavor:
  - [ X ] Developer
  - [ ] Professional
  - [ ] Enterprise

**Comment by nirinchev** [comment] 2017-12-21 00:15
This is a duplicate of https://github.com/realm/realm-dotnet/issues/1411. Unfortunately, it's somewhat annoying to fix and hasn't been a huge priority since the only way it manifests is by outputting build warnings.

**Closed by nirinchev** 2017-12-21 00:15 UTC
