### ISSUE TITLE
Query with cast began failing in beta2 release

### ISSUE THREAD

**Issue by peppy** [realm/realm-dotnet#2392] opened 2021-05-25 08:12 UTC
On `10.2.0-beta.1` the following queries work as expected:

```csharp
var count = realmFactory.Context.All<RealmKeyBinding>().Count(b => (GlobalAction)b.ActionInt == globalAction);
```

```csharp
var count = realmFactory.Context.All<RealmKeyBinding>().Count(b => b.ActionInt == (int)globalAction);
```

On `10.2.0-beta2` they throw the following exception:

```csharp
TearDown : System.AggregateException : One or more errors occurred. (No conversion exists from osu.Game.Input.Bindings.GlobalAction to System.Int64)
  ----> System.NotSupportedException : No conversion exists from osu.Game.Input.Bindings.GlobalAction to System.Int64
--TearDown
   at osu.Framework.Testing.TestScene.checkForErrors()
   at osu.Framework.Testing.TestScene.RunTests()
--NotSupportedException
   at Realms.Helpers.Operator.Convert[TResult](Object value)
   at Realms.RealmResultsVisitor.AddQueryForConvertibleTypes(SharedRealmHandle realm, IntPtr propertyIndex, Object value, Type columnType, QueryAction action)
   at Realms.RealmResultsVisitor.AddQueryEqual(QueryHandle queryHandle, String columnName, Object value, Type columnType)
   at Realms.RealmResultsVisitor.VisitBinary(BinaryExpression node)
   at Realms.RealmResultsVisitor.VisitMethodCall(MethodCallExpression node)
   at Realms.RealmResults`1.GetOrCreateHandle()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Realms.RealmCollectionBase`1.Enumerator..ctor(RealmCollectionBase`1 parent)
   at Realms.RealmCollectionBase`1.GetEnumerator()
   at osu.Game.Input.RealmKeyBindingStore.GetReadableKeyCombinationsFor(GlobalAction globalAction)+MoveNext() in /Users/dean/Projects/osu/osu.Game/Input/RealmKeyBindingStore.cs:line 33
```

Relevant classes:

```csharp
// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
// See the LICENCE file in the repository root for full licence text.

using System;
using osu.Framework.Input.Bindings;
using osu.Game.Database;
using Realms;

namespace osu.Game.Input.Bindings
{
    [MapTo(nameof(KeyBinding))]
    public class RealmKeyBinding : RealmObject, IHasGuidPrimaryKey, IKeyBinding
    {
        [PrimaryKey]
        public Guid ID { get; set; } = Guid.NewGuid();

        public int? RulesetID { get; set; }

        public int? Variant { get; set; }

        public KeyCombination KeyCombination
        {
            get => KeyCombinationString;
            set => KeyCombinationString = value.ToString();
        }

        public object Action
        {
            get => ActionInt;
            set => ActionInt = (int)value;
        }

        [MapTo(nameof(Action))]
        public int ActionInt { get; set; }

        [MapTo(nameof(KeyCombination))]
        public string KeyCombinationString { get; set; }
    }

    public enum GlobalAction
    {
        [Description("Toggle chat overlay")]
        ToggleChat,

        [Description("Toggle social overlay")]
        ToggleSocial,

        [Description("Reset input settings")]
        ResetInputSettings,

        [Description("Toggle toolbar")]
        ToggleToolbar,

        [Description("Toggle settings")]
        ToggleSettings,

        [Description("Toggle beatmap listing")]
        ToggleBeatmapListing,

        [Description("Increase volume")]
        IncreaseVolume,

        [Description("Decrease volume")]
        DecreaseVolume,

        [Description("Toggle mute")]
        ToggleMute,

        // In-Game Keybindings
        [Description("Skip cutscene")]
        SkipCutscene,

        [Description("Quick retry (hold)")]
        QuickRetry,

        [Description("Take screenshot")]
        TakeScreenshot,

        [Description("Toggle gameplay mouse buttons")]
        ToggleGameplayMouseButtons,

        [Description("Back")]
        Back,

        [Description("Increase scroll speed")]
        IncreaseScrollSpeed,

        [Description("Decrease scroll speed")]
        DecreaseScrollSpeed,

        [Description("Select")]
        Select,

        [Description("Quick exit (hold)")]
        QuickExit,

        // Game-wide beatmap music controller keybindings
        [Description("Next track")]
        MusicNext,

        [Description("Previous track")]
        MusicPrev,

        [Description("Play / pause")]
        MusicPlay,

        [Description("Toggle now playing overlay")]
        ToggleNowPlaying,

        [Description("Previous selection")]
        SelectPrevious,

        [Description("Next selection")]
        SelectNext,

        [Description("Home")]
        Home,

        [Description("Toggle notifications")]
        ToggleNotifications,

        [Description("Pause gameplay")]
        PauseGameplay,

        // Editor
        [Description("Setup mode")]
        EditorSetupMode,

        [Description("Compose mode")]
        EditorComposeMode,

        [Description("Design mode")]
        EditorDesignMode,

        [Description("Timing mode")]
        EditorTimingMode,

        [Description("Hold for HUD")]
        HoldForHUD,

        [Description("Random skin")]
        RandomSkin,

        [Description("Pause / resume replay")]
        TogglePauseReplay,

        [Description("Toggle in-game interface")]
        ToggleInGameInterface,

        // Song select keybindings
        [Description("Toggle Mod Select")]
        ToggleModSelection,

        [Description("Random")]
        SelectNextRandom,

        [Description("Rewind")]
        SelectPreviousRandom,

        [Description("Beatmap Options")]
        ToggleBeatmapOptions,

        [Description("Verify mode")]
        EditorVerifyMode,

        [Description("Nudge selection left")]
        EditorNudgeLeft,

        [Description("Nudge selection right")]
        EditorNudgeRight,

        [Description("Toggle skin editor")]
        ToggleSkinEditor,
    }
}
```

As this is a regression between two betas, I haven't immediately created an isolated fail case for this as it is likely you will be able to find the cause quite readily. Let me know if you need further information.

**Comment by nirinchev** [comment] 2021-05-25 09:09
Yes - this is due to a change that sought to remove dynamic lambda compilation and execution from our query engine. Previously we'd dynamically compile and invoke the convert expression and work with the returned value (the int), but on top of this being fairly slow for platforms like iOS, it doesn't work at all on Unity. We still handle conversions with a statically defined converters, but those only work with system and Realm types - they won't work with your custom enum.

I can try and see if using Convert.ChangeType will be feasible as a fallback - it'll be slightly slower, but at least will hopefully be able to handle simple conversions like this one.

In the meantime, a workaround would be to move the conversion outside of the expression:

```csharp
var myEnumInt = (int)MyEnum.SomeValue;
car results = realm.All<Foo>().Where(f => f.EnumInt == myEnumInt);
```

**Comment by peppy** [comment] 2021-05-25 12:11
Yep, I had that exact workaround as well. But it does seem like a weird quirk which would better be addressed, or at least explained with an exception that isn't a hard-to-understand cast failure.

**Comment by nirinchev** [comment] 2021-05-25 12:27
Agreed - it's a breaking change that we overlooked and we'll try to get it sorted out before the final release.

**Comment by nirinchev** [comment] 2021-05-28 13:19
@peppy I tried reproducing the error and couldn't with -beta.2. Here's the dumbed-down test case that I added based on your description:

```csharp
public class RealmKeyBinding : RealmObject
{
    [PrimaryKey]
    public Guid ID { get; set; } = Guid.NewGuid();

    public int ActionInt { get; set; }
}

public enum GlobalAction
{
    ToggleChat,

    ToggleSocial,

    ToggleSkinEditor,
}

[Test]
public void Test_2392()
{
    var globalAction = GlobalAction.ToggleChat;
    var count = _realm.All<RealmKeyBinding>().Count(b => b.ActionInt == (int)globalAction);
}
```

**Comment by peppy** [comment] 2021-05-31 16:59
Apologies, I was trying to simplify it but in the process I think i avoided the issue altogether. It looks to be fine for `Count` but not for `Where`:

![IMG_0037](https://user-images.githubusercontent.com/191335/120223662-e776fc00-c27c-11eb-8dcc-81e3fbbcd681.jpeg)

**Comment by nirinchev** [comment] 2021-06-04 11:44
Okay, I have a fix for this and I expect it'll land in the final 10.2.0 release. Thanks again for reporting this!

**Closed** 2021-06-04 13:35 UTC
Labels: O-Community
