### ISSUE TITLE
SubscribeForNotifications not called with initial "changes" value null after subscription

### ISSUE THREAD

**Issue by softlion** [realm/realm-dotnet#3283] opened 2023-04-02 10:43 UTC
### What happened?

From the doc of `SubscribeForNotifications`: https://www.mongodb.com/docs/realm/sdk/dotnet/react-to-changes/

> Realm emits an initial notification when a subscription is added. After the initial notification, Realm delivers notifications asynchronously whenever a write transaction adds, modifies, or removes objects in the collection.

It looks like the doc is misleading.  
The handler is never called after subscribing ?

### Repro steps

I have some code like this:
```        
   var db = Realm.GetInstance(new InMemoryConfiguration("unittests"));
   //...
  disposables.Add(items.SubscribeForNotifications((dbItems, changes, error) => 
{ 
   //code in handler...
});
```

Then some code like this in a unit test:
```
      // SubscribeForNotifications never called before
     await db.RefreshAsync(); //Force realm to refresh and call subscriptions when running on background thread
      // SubscribeForNotifications never called after
```

"code in handler" is never executed after adding the subscription.  
If a property of one "items" is changed, the handler is called the 1st time with changes=null (as expected for a 1st time). But this 1st time is called way too late.

So that means the doc is misleading.  
The handler is never called after subscribing ?

### Version

10.21.0

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Console/Server

### Client OS and version

xunit unit test on .net7

**Comment by nirinchev** [comment] 2023-04-02 12:53
Can you reproduce this in an isolated app? The documentation should be correct and you've probably run into a bug but I'm not able to reproduce it on my MacBook in a .net 6 console application.

**Comment by softlion** [comment] 2023-04-02 15:19
So I coded a repro on .net7 console and it is working as expected.

I moved the same code in a xunit test (net7 too) and it fails to run with `The class SomeItem is not in the limited set of classes for this realm (Parameter 'objectType')` that I have no clue where it comes from. 

Here the code:
- create a .net7 unit test project with xunit (I'm using rider and the default template for this project type).
- paste that code and debug the unit test

```csharp
using System;
using System.Linq;
using Xunit;
using Realms;
using Xunit.Abstractions;

namespace My.Tests;


public class RealmSubscriptionTest
{
    private readonly ITestOutputHelper output;

    public RealmSubscriptionTest(ITestOutputHelper testOutputHelper)
    {
        output = testOutputHelper;
    }

    [Fact]
    public void TestSubscription()
    {
        var db = Realm.GetInstance(new InMemoryConfiguration("unittests"));

        db.Write(() =>
        {
            db.Add(new SomeItem {SomeField = 1});
        });
        db.Refresh();

        output.WriteLine("Subscribing to db");
        var allItems = db.All<SomeItem>();
        allItems.SubscribeForNotifications((items,changeSet,ex) =>
        {
            output.WriteLine($"Notification received, changeSet:{(changeSet==null ? "null" : "non null")}");
        });
        db.Refresh();
        output.WriteLine("Done subscribed to db");

        output.WriteLine("Updating a field in db");
        db.Write(() => { allItems.First().SomeField = 2; });
        db.Refresh();
        output.WriteLine("Done updating a field in db");
    }
}

public partial class SomeItem : IRealmObject
{
    public int SomeField { get; set; }
}
```

**Comment by softlion** [comment] 2023-04-03 07:39
Ok it looks like you have to add Task.Delay in unit tests and that work as expected. Closing.

**Comment by nirinchev** [comment] 2023-04-03 12:55
Are you calling the API asynchronously? If so, I don't imagine there's a scenario where you get the API results before the initial notification is delivered. If you block the main thread though, the notification will only get delivered once the thread is released.

**Comment by softlion** [comment] 2023-04-04 06:30
It looks like this unit test always pass when run without debugging.  
But never pass when run with debugging.  
I tried adding Task.Delay to simulate the slower timings in debugging mode without success: without debugging it always pass.  

Maybe there is something related to multithreading that is disabled while debugging ?

Without debugging:
```
Subscribing to db
Done subscribed to db
Adding item
Notification received, changeSet:null
value received: 0
waiting 1st notification
Notification received, changeSet:non null
value received: 1
waiting 2nd notification
all's good
```

With debugging:
```
Subscribing to db
Done subscribed to db
Adding item
Notification received, changeSet:null
value received: 0
waiting 1st notification
waiting 2nd notification
Assert.Equal() Failure
Expected: 1
Actual:   -1
```


```
using System;
using System.Linq;
using System.Reactive.Linq;
using System.Reactive.Subjects;
using System.Threading.Tasks;
using Xunit;
using Realms;
using Watchium.Lib.Utilities;
using Xunit.Abstractions;
...

          [Fact]
    public async Task TestSubscriptionOnEmptyDb()
    {
        using var db = Realm.GetInstance(new InMemoryConfiguration("unittests"));
        db.Error += (sender, args) => output.WriteLine(args.Exception.ToLongString());
        
        using var notificationReceivedSubject = new ReplaySubject<int>();
        using var logSubscription = notificationReceivedSubject.Subscribe(value => output.WriteLine($"value received: {value}"));

        output.WriteLine("Subscribing to db");
        var allItems = db.All<SomeItem>();
        using var subscription = allItems.SubscribeForNotifications(async (items, changeSet, ex) =>
        {
            output.WriteLine($"Notification received, changeSet:{(changeSet == null ? "null" : "non null")}");
            notificationReceivedSubject.OnNext(changeSet == null ? 0 : 1);
        });
        output.WriteLine("Done subscribed to db");

        output.WriteLine("Adding item");
        db.Write(() => { db.Add(new SomeItem { SomeField = 1 }); });

        output.WriteLine("waiting 1st notification");
        var result = await notificationReceivedSubject.Amb(Observable.Return(-1).Delay(TimeSpan.FromSeconds(2))).FirstAsync();
        Assert.Equal(0, result);
        
        output.WriteLine("waiting 2nd notification");
        result = await notificationReceivedSubject.Skip(1).Amb(Observable.Return(-1).Delay(TimeSpan.FromSeconds(2))).FirstAsync();
        Assert.Equal(1, result);

        output.WriteLine("all's good");
    }
```

**Comment by nirinchev** [comment] 2024-02-01 10:53
We haven't been able to reproduce this, so I'll close it.

**Closed by nirinchev** 2024-02-01 10:53 UTC
Labels: T-Bug, O-Community, SDK-Use:Local
