### ISSUE TITLE
The "RealmBuildTasks.WeaveRealmAssembly" task failed unexpectedly

### ISSUE THREAD

**Issue by andnes-cap** [realm/realm-dotnet#1274] opened 2017-03-13 12:40 UTC
After updating to Realm 1.1.0, Visual Studio fails to build my Xamarin iOS application. The following errors appear in Output:

The "RealmBuildTasks.WeaveRealmAssembly" task failed unexpectedly.
System.Exception: Realm is referenced by your project but was not found in C:\ws\Njord\Mobile\Dev\Client\Njord.Iphone\bin\iPhone\Debug\. Make sure that CopyLocal is set to True and try again.

I double-checked to make sure that Copy Local was set to True, and it was (for both Realm and Realm.Sync). 

#### Version of Realm and tooling
Realm version(s): 1.1.0

Xamarin/Visual Studio version: 
Visual Studio Enterprise 2015 Update 3
Xamarin 4.3.0.784
Xamarin.iOS 10.4.0.123

Mac Build Host:
XCode 8.2.1
Xamarin Studio 6.2
Xamarin.iOS 10.4.0.123

Which operating system version and device: 
Windows 10 Pro

**Comment by nirinchev** [comment] 2017-03-13 13:25
This is a duplicate of https://github.com/realm/realm-dotnet/issues/1265. I've updated its title to be easier to find. There is a bug with 1.1.0 that prevents compilation on Visual Studio for iOS. The only workarounds are to revert to 1.0.4 or build using Xamarin Studio.

**Closed by nirinchev** 2017-03-13 13:25 UTC
Labels: T:Duplicate
