### ISSUE TITLE
"Attempted to access detached row"

### ISSUE THREAD

**Issue by PaulARoy** [realm/realm-dotnet#754] opened 2016-08-04 15:51 UTC
#### Error
I keep getting the exception "Attempted to access detached row". As I found nothing on the internet I thought I might ask directly here..

I do not understand why this happens and what causes this issue. I do not have the feeling to do anything wrong (at least my code does not work very differently from SQLite).

#### Steps & Code to Reproduce

PCL + Xamarin.iOS. I load a bunch of data from a service in a PCL project that are forwarded to a viewcontroller.
The first call is okay but the second view make another call (quite similar) and I keep getting this error.

#### Version of Realm and tooling
Realm version: 0.77.1
Xamarin/Visual Studio version: VS Enterprise 2015

Which operating system version and device: ?
iOS (iPhone or Simulator), dev on Windows and Visual studio

**Comment by CrimsonKyle** [comment] 2016-08-04 15:53
#746

**Comment by PaulARoy** [comment] 2016-08-04 16:09
Thanks I did not find this issue

**Comment by AndyDentFree** [comment] 2016-08-05 06:56
Closed as duplicate of #746

**Closed by AndyDentFree** 2016-08-05 06:56 UTC
Labels: T:Duplicate
