### ISSUE TITLE
Error "Fody/RealmWeaver - Class XXX is a RealmObject but has no persisted properties" throws when third party controls are used

### ISSUE THREAD

**Issue by DineshBabuYadav** [realm/realm-dotnet#1484] opened 2017-07-17 08:44 UTC
Hi Team,

I have downloaded the Realm packages from [Nuget](https://www.nuget.org/) and implemented with third party control i.e., SfListView(Sycnfusion Control) similar to Xamarin Forms ListView. And tried to deploy in XF Android and other platforms too. But i am facing the following exception has been thrown at our end.

**Fody/RealmWeaver - Class XXX is a RealmObject but has no persisted properties**

For your reference, we have attached the ensured sample at our end and you can download it from the below link
[ListViewRealm.zip](https://github.com/realm/realm-dotnet/files/1151977/ListViewRealm.zip)

Could you please check with the above sample and help me to resolve the reported issue to proceed further?
 
**Xamarin Forms version :** 2.3.4.247 
**Realm.Database version :**1.5.0
**Realm version :** 1.1.0
**Fody :** 2.0.6

Regards,
Dinesh Babu Yadav

**Comment by nirinchev** [comment] 2017-07-19 08:08
Hi Dinesh,

As the error message says, the problem is that you have declared `Contacts` as inheriting `RealmObject`, but none of its properties are automatic (just a getter and setter). This tells Realm to ignore them ([docs here](https://realm.io/docs/xamarin/latest/#custom-setters)) and thus leaves the object with no persisted properties, which is an error.

**Comment by nirinchev** [comment] 2017-08-05 10:16
Dinesh, did that help, should I close the issue or are you still facing the problem?

**Comment by nirinchev** [comment] 2017-08-09 12:39
I'll close the issue due to inactivity. If you need further help, feel free to reopen it.

**Closed by nirinchev** 2017-08-09 12:39 UTC
Labels: S:Waiting For User, T:Help

**Comment by shinriyo** [comment] 2018-04-01 14:07
iOS and Android project could install FodyHelpers but can't.
```
Could not install package 'FodyHelpers 3.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**Comment by nirinchev** [comment] 2018-04-01 19:18
@shinriyo please refrain from commenting on closed issues that appear to be unrelated to your problem. If you're having difficulty installing or using Realm, please file a new issue and fill in all the information in the template. Thanks.
