### ISSUE TITLE
The Realm File stores data in an outdated format

### ISSUE THREAD

**Issue by pornganizer** [realm/realm-dotnet#1993] opened 2020-07-18 00:42 UTC
## Goals

Update a realm database in production that is created via a .NET app to the latest format. 

## Expected Results

Update database files created through my application to the latest version so they can also be opened in Realm Studio.

## Actual Results

When opening a database file via Realm Studio, I am presented with the following dialog:

![image](https://user-images.githubusercontent.com/21695807/87840222-8022aa00-c86c-11ea-9491-bf9d1f97d9ca.png)

## Steps to Reproduce

Open any database file created through my realm .net application in Realm Studio

## Code Sample

I cannot provide a full reproduction of this issue.
I have performed several schema changes a couple migrations while this issue persists (my understanding is that a migration, along with running all the latest nuget packages should have updated the database to the latest format).

I am hoping that providing details on my setup may give some hints as to why this is happening.

PG.RealmDatabase - a c# class library targetting .NET Standard 2.0
PGV5 - a WPF app targetting .NET 4.8 that references PG.RealmDatabase

screenshot of my project setup if perhaps that helps?
![image](https://user-images.githubusercontent.com/21695807/87845919-d823d580-c899-11ea-99f3-93594eb567b7.png)

I have followed these steps:

![image](https://user-images.githubusercontent.com/21695807/87841466-66389580-c873-11ea-997e-782353efd673.png)

## Version of Realm and Tooling

- Realm Object Server Version: i'm not sure how to provide this given my issue
- Flavor:
  - [ ] Realm Cloud
  - [ x ] Self-Hosted
- Client SDK Version: Realm 4.3.0 + Realm.Fody 4.3.0
- Client OS & Version: Windows 10 Pro

Is there any more information I can provide that may help in narrowing down this issue? I'm aware this question is a bit scant on details.

**Comment by nirinchev** [comment] 2020-07-18 07:45
The reason for this dialog is that Realm studio uses a newer version of Realm Core (the database engine used by all Realm SDKs). The .NET SDK hasn't been updated to that version yet, but we do have plans to upgrade it.

The version used by the .NET SDK is stable and production ready, so it's not a problem to continue using it for the foreseeable future.

**Comment by pornganizer** [comment] 2020-07-18 12:11
Is there a version of Realm Studio I can use that will work with the current database version?

**Comment by nirinchev** [comment] 2020-07-18 14:20
Studio can open the file, the problem is that once you upgrade it, you won't be able to open it with the .NET SDK - is this your use case?

**Comment by pornganizer** [comment] 2020-07-18 17:40
yes exactly

**Comment by nirinchev** [comment] 2020-07-19 15:42
@kraenhansen can you help with a link to the last Studio version that uses Realm Core 5.x?

**Comment by luccasclezar** [comment] 2020-07-22 15:56
> The reason for this dialog is that Realm studio uses a newer version of Realm Core (the database engine used by all Realm SDKs). The .NET SDK hasn't been updated to that version yet, but we do have plans to upgrade it.
> 
> The version used by the .NET SDK is stable and production ready, so it's not a problem to continue using it for the foreseeable future.

Hey @nirinchev, would you mind giving a timeframe for the MongoDB Realm .NET SDK release? No one says a thing about it besides "it will be released someday".

Even if it's going to take 10 years to release it, it's better to say that than to let developers in the dark.

**Comment by nirinchev** [comment] 2020-07-22 16:03
We can't commit to dates yet. We're working on it and hope to share more information in the near future. That being said, if the availability of a .net SDK is critical for a project you're working on, please reach out to your account executive and they may be able to share more details than are publicly available.

**Comment by geragray** [comment] 2020-07-28 10:13
@luccasclezar we have added Core6 file format upgrade option to Studio 3.11 and recommending using 3.10 for all Core5 users. You can download it here https://studio-releases.realm.io/

**Closed** 2020-08-06 11:23 UTC
Labels: O-Community
