### ISSUE TITLE
Assertion failed while filtering on a realm result set "!m_sg" 1.2.0

### ISSUE THREAD

**Issue by CrimsonKyle** [realm/realm-dotnet#1339] opened 2017-04-06 16:14 UTC
I am receiving this while Linq filtering on a realm result set. Appears to be related to the new collection notification system.

```
/Users/realm/workspace/realm_realm-dotnet_PR-1327-AUFWTQFJR54PSYKP2BJSJVD4IYEHKXDMD5WNDNSS4XV3I2NVTHTA/wrappers/src/object-store/src/impl/collection_notifier.cpp:378: [realm-core-2.5.1] Assertion failed: !m_sg
0   AltecService.iOS                    0x0016cda0 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 48
1   AltecService.iOS                    0x0016d11c _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 492
2   AltecService.iOS                    0x000db98b _ZN5realm5_impl18CollectionNotifier9attach_toERNS_11SharedGroupE + 73
3   AltecService.iOS                    0x0009ecb2 _ZN5realm5_impl16RealmCoordinator19run_async_notifiersEv + 1164
4   AltecService.iOS                    0x0009e7d4 _ZN5realm5_impl16RealmCoordinator9on_changeEv + 20
5   AltecService.iOS                    0x000c79c4 _ZN5realm5_impl20ExternalCommitHelper6listenEv + 194
6   AltecService.iOS                    0x000c7c79 _ZNSt3__112__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS2_16RealmCoordinatorEE3$_0JEEclEv + 25
7   AltecService.iOS                    0x000c7bfb _ZNSt3__119__async_assoc_stateIvNS_12__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS3_16RealmCoordinatorEE3$_0JEEEE9__executeEv + 19
8   AltecService.iOS                    0x000c7dc0 _ZNSt3__114__thread_proxyINS_5tupleIJMNS_19__async_assoc_stateIvNS_12__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS5_16RealmCoordinatorEE3$_0JEEEEEFvvEPSB_EEEEEPvSG_ + 76
9   libsystem_pthread.dylib             0x0c90410b _pthread_body + 184
10  libsystem_pthread.dylib             0x0c904053 _pthread_body + 0
11  libsystem_pthread.dylib             0x0c90390e thread_start + 34
IMPORTANT: if you see this error, please send this log to help@realm.io.2017-04-06 11:09:37.549 AltecService.iOS[84911:625544] critical: Stacktrace:
```

**Comment by nirinchev** [comment] 2017-04-06 16:33
Sounds like it is - can you share more details on the code that prompts this error?

**Comment by CrimsonKyle** [comment] 2017-04-06 21:26
Certainly!

This is the Code:

```
searchBar.TextChanged += SearchItems;
ListView.ItemSource = data;

void SearchItems(object sender, TextChangedEventArgs e)
		{
			if (data != null)
			{
				ListView.BeginRefresh();

				var filter = e.NewTextValue;
				System.Console.WriteLine("Searching On: {0}", filter);

				if (string.IsNullOrWhiteSpace(filter))
				{
					ListView.ItemsSource = data;
				}
				else
				{
					ListView.ItemsSource = data.Where(sr => (sr.Customer.ToLower().Contains(filter.ToLower()))
										  || (sr.Summary.ToLower().Contains(filter.ToLower()))
										  || (sr.SrNumber.ToLower().Contains(filter.ToLower()))
										  || (sr.SrId.ToLower().Contains(filter.ToLower()))
										  || (sr.ScheduledDate.ToString().ToLower().Contains(filter.ToLower()))).ToList();
				}
				ListView.EndRefresh();
			}
}

```
This is the Console Output:
```
2017-04-06 11:09:36.936 AltecService.iOS[84911:625293] Searching On: Ser
2017-04-06 11:09:37.525 AltecService.iOS[84911:625293] Searching On: Se
/Users/realm/workspace/realm_realm-dotnet_PR-1327-AUFWTQFJR54PSYKP2BJSJVD4IYEHKXDMD5WNDNSS4XV3I2NVTHTA/wrappers/src/object-store/src/impl/collection_notifier.cpp:378: [realm-core-2.5.1] Assertion failed: !m_sg
0   AltecService.iOS                    0x0016cda0 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 48
1   AltecService.iOS                    0x0016d11c _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 492
2   AltecService.iOS                    0x000db98b _ZN5realm5_impl18CollectionNotifier9attach_toERNS_11SharedGroupE + 73
3   AltecService.iOS                    0x0009ecb2 _ZN5realm5_impl16RealmCoordinator19run_async_notifiersEv + 1164
4   AltecService.iOS                    0x0009e7d4 _ZN5realm5_impl16RealmCoordinator9on_changeEv + 20
5   AltecService.iOS                    0x000c79c4 _ZN5realm5_impl20ExternalCommitHelper6listenEv + 194
6   AltecService.iOS                    0x000c7c79 _ZNSt3__112__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS2_16RealmCoordinatorEE3$_0JEEclEv + 25
7   AltecService.iOS                    0x000c7bfb _ZNSt3__119__async_assoc_stateIvNS_12__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS3_16RealmCoordinatorEE3$_0JEEEE9__executeEv + 19
8   AltecService.iOS                    0x000c7dc0 _ZNSt3__114__thread_proxyINS_5tupleIJMNS_19__async_assoc_stateIvNS_12__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS5_16RealmCoordinatorEE3$_0JEEEEEFvvEPSB_EEEEEPvSG_ + 76
9   libsystem_pthread.dylib             0x0c90410b _pthread_body + 184
10  libsystem_pthread.dylib             0x0c904053 _pthread_body + 0
11  libsystem_pthread.dylib             0x0c90390e thread_start + 34
IMPORTANT: if you see this error, please send this log to help@realm.io.2017-04-06 11:09:37.549 AltecService.iOS[84911:625544] critical: Stacktrace:
```

**Comment by Shaddix** [comment] 2017-04-10 04:45
having the same issue

**Comment by nirinchev** [comment] 2017-04-11 01:19
Shaddix, do you think you'll be able to share a stripped-down project we can use to reproduce and debug the issue? If you are concerned about sharing it publicly, feel free to email us at help@realm.io.

**Comment by Obvious1992** [comment] 2017-04-11 08:38
Facing the same in the current stable Nuget.

**Comment by nirinchev** [comment] 2017-04-11 12:07
I'm going to need more information to be able to reproduce and debug this issue. I tried going off of @CrimsonKyle's code but my simplified case works just fine. If any of you can share a project or a stripped-down example that reproduces the issue, that would speed up the debugging efforts greatly!

**Comment by jimespen** [comment] 2017-04-28 07:35
@nirinchev I sent you guys an email yesterday about this same console output and I also attached the crash log from HockeyApp which I'm using for beta testing the app with our production backend. At the time I wrote the email (with subject: "Realm Mobile Database crashes in production environment") I thought it seemed fine in our stage/testing environment, but I've ruled that out since then.

I don't have any issues with filtering, though. My issue is that I have a list of objects stored in Realm, and the app crashes if I scroll the list in iOS. Unfortunately I'm unable to share any code with you, but I hope the email is of some use.

**Comment by jimespen** [comment] 2017-04-28 10:59
@nirinchev I sent you guys an email yesterday about this same console output and I also attached the crash log (that I unfortunately forgot to symbolicate, but I sent a symbolicated one today).

I don't have any issues with filtering, though. My issue is that I have a list of objects retrieved from Realm, and the app crashes if I scroll the list in iOS. Unfortunately I'm unable to share any code with you, but I hope the email is of some use.

**Comment by nirinchev** [comment] 2017-04-28 12:36
Thanks! This issue is our high on our priority list, so as soon as someone is available, we'll try to tackle it.

**Comment by iWeaverMan** [comment] 2017-05-02 11:08
+1
App crashes if I scroll the list in iOS
1.2.1

**Comment by nirinchev** [comment] 2017-05-02 17:03
If someone who is able to reproduce this crash is willing to test, I [here is a prerelease version](https://drive.google.com/file/d/0B45yfBWnWXwAMXVoUWw2N0JKczQ/view?usp=sharing) of Realm 1.3.0. It contains a few fixes around notifications, so it might address the current problem (I am unable to confirm as I have been unsuccessful at reproducing it).

**Comment by jimespen** [comment] 2017-05-03 09:28
I tested the prerelease, and it's seems to be solved now. In my case at least, the iOS app does not crash anymore. I am experiencing other (probably unrelated) issues with cell reuse in the list, but that's probably either an iOS thing or, more likely, a case of PEBKAC. Thanks, @nirinchev!

**Comment by nirinchev** [comment] 2017-05-03 14:31
Glad to hear it works for you! I'll close the issue, but if anyone else runs into it with the prerelease version, ping me and I'll reopen it.

**Closed by nirinchev** 2017-05-03 14:31 UTC
Labels: S:P1 Backlog, T:Bug-Crash
